// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/ml/v1beta1/model_service.proto

package google_cloud_ml_v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "go.pedge.io/pb/go/google/api"
import _ "go.pedge.io/pb/go/google/api"
import _ "go.pedge.io/pb/go/google/longrunning"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Represents a machine learning solution.
//
// A model can have multiple versions, each of which is a deployed, trained
// model ready to receive prediction requests. The model itself is just a
// container.
type Model struct {
	// Required. The name specified for the model when it was created.
	//
	// The model name must be unique within the project it is created in.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Optional. The description specified for the model when it was created.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// Output only. The default version of the model. This version will be used to
	// handle prediction requests that do not specify a version.
	//
	// You can change the default version by calling
	// [projects.methods.versions.setDefault](/ml/reference/rest/v1beta1/projects.models.versions/setDefault).
	DefaultVersion *Version `protobuf:"bytes,3,opt,name=default_version,json=defaultVersion" json:"default_version,omitempty"`
	// Optional. The list of regions where the model is going to be deployed.
	// Currently only one region per model is supported.
	// Defaults to 'us-central1' if nothing is set.
	Regions []string `protobuf:"bytes,4,rep,name=regions" json:"regions,omitempty"`
	// Optional. If true, enables StackDriver Logging for online prediction.
	// Default is false.
	OnlinePredictionLogging bool `protobuf:"varint,5,opt,name=online_prediction_logging,json=onlinePredictionLogging" json:"online_prediction_logging,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Model) GetDefaultVersion() *Version {
	if m != nil {
		return m.DefaultVersion
	}
	return nil
}

func (m *Model) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Model) GetOnlinePredictionLogging() bool {
	if m != nil {
		return m.OnlinePredictionLogging
	}
	return false
}

// Represents a version of the model.
//
// Each version is a trained model deployed in the cloud, ready to handle
// prediction requests. A model can have multiple versions. You can get
// information about all of the versions of a given model by calling
// [projects.models.versions.list](/ml/reference/rest/v1beta1/projects.models.versions/list).
type Version struct {
	// Required.The name specified for the version when it was created.
	//
	// The version name must be unique within the model it is created in.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Optional. The description specified for the version when it was created.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// Output only. If true, this version will be used to handle prediction
	// requests that do not specify a version.
	//
	// You can change the default version by calling
	// [projects.methods.versions.setDefault](/ml/reference/rest/v1beta1/projects.models.versions/setDefault).
	IsDefault bool `protobuf:"varint,3,opt,name=is_default,json=isDefault" json:"is_default,omitempty"`
	// Required. The Google Cloud Storage location of the trained model used to
	// create the version. See the
	// [overview of model deployment](/ml/docs/concepts/deployment-overview) for
	// more informaiton.
	//
	// When passing Version to
	// [projects.models.versions.create](/ml/reference/rest/v1beta1/projects.models.versions/create)
	// the model service uses the specified location as the source of the model.
	// Once deployed, the model version is hosted by the prediction service, so
	// this location is useful only as a historical record.
	DeploymentUri string `protobuf:"bytes,4,opt,name=deployment_uri,json=deploymentUri" json:"deployment_uri,omitempty"`
	// Output only. The time the version was created.
	CreateTime *google_protobuf2.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	// Output only. The time the version was last used for prediction.
	LastUseTime *google_protobuf2.Timestamp `protobuf:"bytes,6,opt,name=last_use_time,json=lastUseTime" json:"last_use_time,omitempty"`
	// Optional. The Google Cloud ML runtime version to use for this deployment.
	// If not set, Google Cloud ML will choose a version.
	RuntimeVersion string `protobuf:"bytes,8,opt,name=runtime_version,json=runtimeVersion" json:"runtime_version,omitempty"`
	// Optional. Manually select the number of nodes to use for serving the
	// model. If unset (i.e., by default), the number of nodes used to serve
	// the model automatically scales with traffic. However, care should be
	// taken to ramp up traffic according to the model's ability to scale. If
	// your model needs to handle bursts of traffic beyond it's ability to
	// scale, it is recommended you set this field appropriately.
	ManualScaling *ManualScaling `protobuf:"bytes,9,opt,name=manual_scaling,json=manualScaling" json:"manual_scaling,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Version) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Version) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Version) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *Version) GetDeploymentUri() string {
	if m != nil {
		return m.DeploymentUri
	}
	return ""
}

func (m *Version) GetCreateTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Version) GetLastUseTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.LastUseTime
	}
	return nil
}

func (m *Version) GetRuntimeVersion() string {
	if m != nil {
		return m.RuntimeVersion
	}
	return ""
}

func (m *Version) GetManualScaling() *ManualScaling {
	if m != nil {
		return m.ManualScaling
	}
	return nil
}

// Options for manually scaling a model.
type ManualScaling struct {
	// The number of nodes to allocate for this model. These nodes are always up,
	// starting from the time the model is deployed, so the cost of operating
	// this model will be proportional to nodes * number of hours since
	// deployment.
	Nodes int32 `protobuf:"varint,1,opt,name=nodes" json:"nodes,omitempty"`
}

func (m *ManualScaling) Reset()                    { *m = ManualScaling{} }
func (m *ManualScaling) String() string            { return proto.CompactTextString(m) }
func (*ManualScaling) ProtoMessage()               {}
func (*ManualScaling) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ManualScaling) GetNodes() int32 {
	if m != nil {
		return m.Nodes
	}
	return 0
}

// Request message for the CreateModel method.
type CreateModelRequest struct {
	// Required. The project name.
	//
	// Authorization: requires `Editor` role on the specified project.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Required. The model to create.
	Model *Model `protobuf:"bytes,2,opt,name=model" json:"model,omitempty"`
}

func (m *CreateModelRequest) Reset()                    { *m = CreateModelRequest{} }
func (m *CreateModelRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateModelRequest) ProtoMessage()               {}
func (*CreateModelRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *CreateModelRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateModelRequest) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

// Request message for the ListModels method.
type ListModelsRequest struct {
	// Required. The name of the project whose models are to be listed.
	//
	// Authorization: requires `Viewer` role on the specified project.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Optional. A page token to request the next page of results.
	//
	// You get the token from the `next_page_token` field of the response from
	// the previous call.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	// Optional. The number of models to retrieve per "page" of results. If there
	// are more remaining results than this number, the response message will
	// contain a valid value in the `next_page_token` field.
	//
	// The default value is 20, and the maximum page size is 100.
	PageSize int32 `protobuf:"varint,5,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *ListModelsRequest) Reset()                    { *m = ListModelsRequest{} }
func (m *ListModelsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListModelsRequest) ProtoMessage()               {}
func (*ListModelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ListModelsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListModelsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListModelsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// Response message for the ListModels method.
type ListModelsResponse struct {
	// The list of models.
	Models []*Model `protobuf:"bytes,1,rep,name=models" json:"models,omitempty"`
	// Optional. Pass this token as the `page_token` field of the request for a
	// subsequent call.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListModelsResponse) Reset()                    { *m = ListModelsResponse{} }
func (m *ListModelsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListModelsResponse) ProtoMessage()               {}
func (*ListModelsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ListModelsResponse) GetModels() []*Model {
	if m != nil {
		return m.Models
	}
	return nil
}

func (m *ListModelsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Request message for the GetModel method.
type GetModelRequest struct {
	// Required. The name of the model.
	//
	// Authorization: requires `Viewer` role on the parent project.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetModelRequest) Reset()                    { *m = GetModelRequest{} }
func (m *GetModelRequest) String() string            { return proto.CompactTextString(m) }
func (*GetModelRequest) ProtoMessage()               {}
func (*GetModelRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetModelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Request message for the DeleteModel method.
type DeleteModelRequest struct {
	// Required. The name of the model.
	//
	// Authorization: requires `Editor` role on the parent project.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteModelRequest) Reset()                    { *m = DeleteModelRequest{} }
func (m *DeleteModelRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteModelRequest) ProtoMessage()               {}
func (*DeleteModelRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *DeleteModelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Uploads the provided trained model version to Cloud Machine Learning.
type CreateVersionRequest struct {
	// Required. The name of the model.
	//
	// Authorization: requires `Editor` role on the parent project.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Required. The version details.
	Version *Version `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *CreateVersionRequest) Reset()                    { *m = CreateVersionRequest{} }
func (m *CreateVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateVersionRequest) ProtoMessage()               {}
func (*CreateVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *CreateVersionRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateVersionRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// Request message for the ListVersions method.
type ListVersionsRequest struct {
	// Required. The name of the model for which to list the version.
	//
	// Authorization: requires `Viewer` role on the parent project.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Optional. A page token to request the next page of results.
	//
	// You get the token from the `next_page_token` field of the response from
	// the previous call.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	// Optional. The number of versions to retrieve per "page" of results. If
	// there are more remaining results than this number, the response message
	// will contain a valid value in the `next_page_token` field.
	//
	// The default value is 20, and the maximum page size is 100.
	PageSize int32 `protobuf:"varint,5,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *ListVersionsRequest) Reset()                    { *m = ListVersionsRequest{} }
func (m *ListVersionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListVersionsRequest) ProtoMessage()               {}
func (*ListVersionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ListVersionsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListVersionsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListVersionsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// Response message for the ListVersions method.
type ListVersionsResponse struct {
	// The list of versions.
	Versions []*Version `protobuf:"bytes,1,rep,name=versions" json:"versions,omitempty"`
	// Optional. Pass this token as the `page_token` field of the request for a
	// subsequent call.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListVersionsResponse) Reset()                    { *m = ListVersionsResponse{} }
func (m *ListVersionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListVersionsResponse) ProtoMessage()               {}
func (*ListVersionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ListVersionsResponse) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *ListVersionsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Request message for the GetVersion method.
type GetVersionRequest struct {
	// Required. The name of the version.
	//
	// Authorization: requires `Viewer` role on the parent project.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetVersionRequest) Reset()                    { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()               {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *GetVersionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Request message for the DeleteVerionRequest method.
type DeleteVersionRequest struct {
	// Required. The name of the version. You can get the names of all the
	// versions of a model by calling
	// [projects.models.versions.list](/ml/reference/rest/v1beta1/projects.models.versions/list).
	//
	// Authorization: requires `Editor` role on the parent project.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteVersionRequest) Reset()                    { *m = DeleteVersionRequest{} }
func (m *DeleteVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteVersionRequest) ProtoMessage()               {}
func (*DeleteVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *DeleteVersionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Request message for the SetDefaultVersion request.
type SetDefaultVersionRequest struct {
	// Required. The name of the version to make the default for the model. You
	// can get the names of all the versions of a model by calling
	// [projects.models.versions.list](/ml/reference/rest/v1beta1/projects.models.versions/list).
	//
	// Authorization: requires `Editor` role on the parent project.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SetDefaultVersionRequest) Reset()                    { *m = SetDefaultVersionRequest{} }
func (m *SetDefaultVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*SetDefaultVersionRequest) ProtoMessage()               {}
func (*SetDefaultVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *SetDefaultVersionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Model)(nil), "google.cloud.ml.v1beta1.Model")
	proto.RegisterType((*Version)(nil), "google.cloud.ml.v1beta1.Version")
	proto.RegisterType((*ManualScaling)(nil), "google.cloud.ml.v1beta1.ManualScaling")
	proto.RegisterType((*CreateModelRequest)(nil), "google.cloud.ml.v1beta1.CreateModelRequest")
	proto.RegisterType((*ListModelsRequest)(nil), "google.cloud.ml.v1beta1.ListModelsRequest")
	proto.RegisterType((*ListModelsResponse)(nil), "google.cloud.ml.v1beta1.ListModelsResponse")
	proto.RegisterType((*GetModelRequest)(nil), "google.cloud.ml.v1beta1.GetModelRequest")
	proto.RegisterType((*DeleteModelRequest)(nil), "google.cloud.ml.v1beta1.DeleteModelRequest")
	proto.RegisterType((*CreateVersionRequest)(nil), "google.cloud.ml.v1beta1.CreateVersionRequest")
	proto.RegisterType((*ListVersionsRequest)(nil), "google.cloud.ml.v1beta1.ListVersionsRequest")
	proto.RegisterType((*ListVersionsResponse)(nil), "google.cloud.ml.v1beta1.ListVersionsResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "google.cloud.ml.v1beta1.GetVersionRequest")
	proto.RegisterType((*DeleteVersionRequest)(nil), "google.cloud.ml.v1beta1.DeleteVersionRequest")
	proto.RegisterType((*SetDefaultVersionRequest)(nil), "google.cloud.ml.v1beta1.SetDefaultVersionRequest")
}

func init() { proto.RegisterFile("google/cloud/ml/v1beta1/model_service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 985 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcf, 0x6f, 0xdc, 0x44,
	0x14, 0x96, 0x93, 0x6c, 0xb2, 0xfb, 0xb6, 0x9b, 0x28, 0x43, 0xa0, 0xcb, 0x42, 0xe8, 0xca, 0x55,
	0xda, 0xd5, 0xa6, 0xb5, 0xc9, 0x82, 0x22, 0x75, 0x81, 0x22, 0x95, 0x48, 0x15, 0x52, 0x23, 0x22,
	0xa7, 0xe5, 0x6a, 0x39, 0xbb, 0x53, 0xe3, 0x62, 0xcf, 0x18, 0xcf, 0x38, 0x82, 0x42, 0x0e, 0x70,
	0xe0, 0xc8, 0x01, 0xc4, 0x95, 0x0b, 0x77, 0xfe, 0x19, 0xee, 0x9c, 0x10, 0x7f, 0x04, 0x27, 0x34,
	0xbf, 0x36, 0xde, 0xec, 0x0f, 0x3b, 0x48, 0xbd, 0x79, 0xde, 0x7c, 0x6f, 0xde, 0x37, 0xef, 0x7b,
	0xef, 0x79, 0x60, 0x3f, 0xa4, 0x34, 0x8c, 0xb1, 0x3b, 0x8a, 0x69, 0x3e, 0x76, 0x93, 0xd8, 0x3d,
	0x3f, 0x38, 0xc3, 0x3c, 0x38, 0x70, 0x13, 0x3a, 0xc6, 0xb1, 0xcf, 0x70, 0x76, 0x1e, 0x8d, 0xb0,
	0x93, 0x66, 0x94, 0x53, 0x74, 0x53, 0x81, 0x1d, 0x09, 0x76, 0x92, 0xd8, 0xd1, 0xe0, 0xce, 0xdb,
	0xfa, 0x94, 0x20, 0x8d, 0xdc, 0x80, 0x10, 0xca, 0x03, 0x1e, 0x51, 0xc2, 0x94, 0x5b, 0xe7, 0xf5,
	0xe2, 0x6e, 0xce, 0xbf, 0xd0, 0xe6, 0xdb, 0xda, 0x1c, 0x53, 0x12, 0x66, 0x39, 0x21, 0x11, 0x09,
	0x5d, 0x9a, 0xe2, 0x6c, 0xca, 0xf7, 0x96, 0x06, 0xc9, 0xd5, 0x59, 0xfe, 0xdc, 0xe5, 0x51, 0x82,
	0x19, 0x0f, 0x92, 0x54, 0x01, 0xec, 0xbf, 0x2c, 0xa8, 0x1d, 0x0b, 0xae, 0x08, 0xc1, 0x1a, 0x09,
	0x12, 0xdc, 0xb6, 0xba, 0x56, 0xaf, 0xe1, 0xc9, 0x6f, 0xd4, 0x85, 0xe6, 0x18, 0xb3, 0x51, 0x16,
	0xa5, 0xe2, 0xd0, 0xf6, 0x8a, 0xdc, 0x2a, 0x9a, 0xd0, 0xa7, 0xb0, 0x35, 0xc6, 0xcf, 0x83, 0x3c,
	0xe6, 0xfe, 0x39, 0xce, 0x98, 0x40, 0xad, 0x76, 0xad, 0x5e, 0x73, 0xd0, 0x75, 0x16, 0xdc, 0xd6,
	0xf9, 0x5c, 0xe1, 0xbc, 0x4d, 0xed, 0xa8, 0xd7, 0xa8, 0x0d, 0x1b, 0x19, 0x0e, 0x05, 0xf9, 0xf6,
	0x5a, 0x77, 0xb5, 0xd7, 0xf0, 0xcc, 0x12, 0x0d, 0xe1, 0x4d, 0x4a, 0xe2, 0x88, 0x60, 0x3f, 0xcd,
	0xf0, 0x38, 0x1a, 0x89, 0xc8, 0x7e, 0x4c, 0xc3, 0x30, 0x22, 0x61, 0xbb, 0xd6, 0xb5, 0x7a, 0x75,
	0xef, 0xa6, 0x02, 0x9c, 0x4c, 0xf6, 0x9f, 0xa8, 0x6d, 0xfb, 0xdf, 0x15, 0xd8, 0x30, 0x11, 0xfe,
	0xdf, 0x15, 0x77, 0x01, 0x22, 0xe6, 0x6b, 0xb2, 0xf2, 0x76, 0x75, 0xaf, 0x11, 0xb1, 0x23, 0x65,
	0x40, 0x7b, 0xb0, 0x39, 0xc6, 0x69, 0x4c, 0xbf, 0x49, 0x30, 0xe1, 0x7e, 0x9e, 0x45, 0xed, 0x35,
	0x79, 0x46, 0xeb, 0xd2, 0xfa, 0x2c, 0x8b, 0xd0, 0x07, 0xd0, 0x1c, 0x65, 0x38, 0xe0, 0xd8, 0x17,
	0x12, 0x48, 0xd6, 0xcd, 0x41, 0xc7, 0x24, 0xc9, 0xe8, 0xe3, 0x3c, 0x35, 0xfa, 0x78, 0xa0, 0xe0,
	0xc2, 0x80, 0x1e, 0x42, 0x2b, 0x0e, 0x18, 0xf7, 0x73, 0xa6, 0xdd, 0xd7, 0x4b, 0xdd, 0x9b, 0xc2,
	0xe1, 0x19, 0x53, 0xfe, 0x77, 0x61, 0x2b, 0xcb, 0x89, 0xf0, 0x9c, 0xa8, 0x54, 0x97, 0x24, 0x37,
	0xb5, 0xd9, 0x64, 0xe8, 0x18, 0x36, 0x93, 0x80, 0xe4, 0x41, 0xec, 0xb3, 0x51, 0x10, 0x8b, 0xf4,
	0x36, 0x64, 0xa4, 0x3b, 0x0b, 0xd5, 0x3c, 0x96, 0xf0, 0x53, 0x85, 0xf6, 0x5a, 0x49, 0x71, 0x69,
	0xef, 0x41, 0x6b, 0x6a, 0x1f, 0xed, 0x40, 0x8d, 0xd0, 0x31, 0x66, 0x52, 0x82, 0x9a, 0xa7, 0x16,
	0xf6, 0x19, 0xa0, 0x4f, 0xe4, 0x65, 0x65, 0x25, 0x7a, 0xf8, 0xab, 0x1c, 0x33, 0x8e, 0xde, 0x80,
	0xf5, 0x34, 0xc8, 0x30, 0xe1, 0x5a, 0x2f, 0xbd, 0x42, 0xef, 0x43, 0x4d, 0x76, 0x97, 0xd4, 0xaa,
	0x39, 0x78, 0x67, 0x31, 0x35, 0x79, 0x9a, 0x02, 0xdb, 0x21, 0x6c, 0x3f, 0x89, 0x18, 0x97, 0x36,
	0x56, 0x16, 0x62, 0x17, 0x20, 0x0d, 0x42, 0xec, 0x73, 0xfa, 0x25, 0x26, 0x5a, 0xcf, 0x86, 0xb0,
	0x3c, 0x15, 0x06, 0xf4, 0x16, 0xc8, 0x85, 0xcf, 0xa2, 0x97, 0x4a, 0xc9, 0x9a, 0x57, 0x17, 0x86,
	0xd3, 0xe8, 0x25, 0xb6, 0x39, 0xa0, 0x62, 0x20, 0x96, 0x52, 0xc2, 0x30, 0x3a, 0x84, 0x75, 0xc9,
	0x43, 0xdc, 0x7c, 0xb5, 0x02, 0x6b, 0x8d, 0x46, 0x77, 0x60, 0x8b, 0xe0, 0xaf, 0xb9, 0x5f, 0xa0,
	0xa3, 0x4a, 0xb4, 0x25, 0xcc, 0x27, 0x86, 0x92, 0xbd, 0x07, 0x5b, 0x8f, 0x31, 0x9f, 0xca, 0xdf,
	0x9c, 0x6a, 0xb7, 0x7b, 0x80, 0x8e, 0x70, 0x8c, 0xaf, 0x64, 0x7a, 0x1e, 0xf2, 0x05, 0xec, 0x28,
	0x4d, 0x4c, 0xbb, 0x96, 0xa4, 0x6c, 0x08, 0x1b, 0xa6, 0xb4, 0x56, 0x2a, 0x0e, 0x00, 0xe3, 0x60,
	0x47, 0xf0, 0x9a, 0x48, 0x99, 0xb6, 0xbf, 0x52, 0x75, 0xbe, 0x83, 0x9d, 0xe9, 0x50, 0x5a, 0x9f,
	0x0f, 0xa1, 0xae, 0xd9, 0x18, 0x85, 0xca, 0xf9, 0x4f, 0x3c, 0x2a, 0xab, 0x74, 0x17, 0xb6, 0x1f,
	0x63, 0x7e, 0x25, 0xa3, 0xf3, 0xb2, 0xdf, 0x87, 0x1d, 0xa5, 0x53, 0x05, 0xac, 0x03, 0xed, 0x53,
	0xcc, 0x8f, 0xa6, 0x86, 0xe9, 0x12, 0xfc, 0xe0, 0x1f, 0x80, 0x1b, 0x52, 0xfe, 0x53, 0xf5, 0x77,
	0x42, 0x3f, 0x59, 0xd0, 0x2c, 0xf4, 0x1f, 0xda, 0x5f, 0x78, 0xf3, 0xd9, 0x2e, 0xed, 0x94, 0x14,
	0xb2, 0x3d, 0xf8, 0xe1, 0xcf, 0xbf, 0x7f, 0x59, 0xb9, 0x67, 0xdf, 0x9e, 0xfc, 0x1a, 0xbf, 0x55,
	0x32, 0x7e, 0x94, 0x66, 0xf4, 0x05, 0x1e, 0x71, 0xe6, 0xf6, 0x2f, 0xd4, 0xef, 0x92, 0x0d, 0x55,
	0xaf, 0xa2, 0x9f, 0x2d, 0x80, 0xcb, 0x1e, 0x42, 0xfd, 0x85, 0x21, 0x66, 0x3a, 0xba, 0xb3, 0x5f,
	0x09, 0xab, 0x44, 0xb7, 0xf7, 0x25, 0xb7, 0x3d, 0x54, 0x85, 0x1b, 0xfa, 0xde, 0x82, 0xba, 0x69,
	0x31, 0xd4, 0x5b, 0x18, 0xe6, 0x4a, 0x17, 0x96, 0xe6, 0x67, 0x0e, 0x07, 0xa1, 0x52, 0x81, 0x81,
	0x26, 0xe0, 0xf6, 0x2f, 0xd0, 0x8f, 0x16, 0x34, 0x0b, 0xfd, 0xbb, 0x44, 0xa9, 0xd9, 0x2e, 0xef,
	0xec, 0x1a, 0x70, 0xe1, 0xc5, 0xe0, 0x7c, 0x66, 0x5e, 0x0c, 0x86, 0x48, 0xbf, 0x12, 0x91, 0xdf,
	0x2c, 0x68, 0x4d, 0x8d, 0x07, 0x74, 0xbf, 0xa4, 0x68, 0xa6, 0x0b, 0xb3, 0x8c, 0xcc, 0xc7, 0x92,
	0xcc, 0x03, 0xdb, 0x59, 0xa2, 0xcc, 0x25, 0x1d, 0xd7, 0x34, 0xe2, 0xd0, 0x8c, 0x14, 0xf4, 0xbb,
	0x05, 0x37, 0x8a, 0x8d, 0x8e, 0xee, 0x2d, 0x2d, 0x8c, 0x2b, 0xa3, 0xa7, 0x73, 0xbf, 0x22, 0x5a,
	0x17, 0xd2, 0xa1, 0xa4, 0xfb, 0x2e, 0xba, 0x26, 0x5d, 0x59, 0xe8, 0x97, 0x03, 0x61, 0x49, 0xa1,
	0xcf, 0x4c, 0x8d, 0x4e, 0xe9, 0x78, 0x9a, 0x47, 0x6a, 0x91, 0xa0, 0x13, 0x46, 0x42, 0xdb, 0x5f,
	0x2d, 0x68, 0x4d, 0x0d, 0x9f, 0x25, 0xda, 0xce, 0x1b, 0x52, 0x65, 0xda, 0x6a, 0x5e, 0xfd, 0xeb,
	0xf2, 0xfa, 0xc3, 0x82, 0xed, 0x99, 0x41, 0x87, 0x0e, 0x16, 0x72, 0x5b, 0x34, 0x14, 0x2b, 0xa4,
	0xee, 0x48, 0x52, 0x7c, 0x68, 0x3f, 0xb8, 0x1e, 0xc5, 0x21, 0x9b, 0x84, 0x1c, 0x5a, 0xfd, 0x47,
	0x87, 0x70, 0x6b, 0x44, 0x93, 0x99, 0x60, 0x41, 0x1a, 0x99, 0x80, 0x8f, 0xb6, 0x8b, 0x83, 0xf8,
	0x44, 0xbc, 0xe2, 0x4e, 0xac, 0xb3, 0x75, 0xf9, 0x9c, 0x7b, 0xef, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xda, 0xac, 0xc5, 0xb4, 0x5d, 0x0c, 0x00, 0x00,
}
