// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: google/cloud/bigquery/datatransfer/v1/transfer.proto

package google_cloud_bigquery_datatransfer_v1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "go.pedge.io/pb/gogo/google/api"
import google_protobuf1 "github.com/gogo/protobuf/types"
import google_protobuf2 "github.com/gogo/protobuf/types"
import _ "go.pedge.io/pb/gogo/google/rpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Represents data transfer type.
type TransferType int32

const (
	// Invalid or Unknown transfer type placeholder.
	TransferType_TRANSFER_TYPE_UNSPECIFIED TransferType = 0
	// Batch data transfer.
	TransferType_BATCH TransferType = 1
	// Streaming data transfer. Streaming data source currently doesn't
	// support multiple transfer configs per project.
	TransferType_STREAMING TransferType = 2
)

var TransferType_name = map[int32]string{
	0: "TRANSFER_TYPE_UNSPECIFIED",
	1: "BATCH",
	2: "STREAMING",
}
var TransferType_value = map[string]int32{
	"TRANSFER_TYPE_UNSPECIFIED": 0,
	"BATCH":                     1,
	"STREAMING":                 2,
}

func (x TransferType) String() string {
	return proto.EnumName(TransferType_name, int32(x))
}
func (TransferType) EnumDescriptor() ([]byte, []int) { return fileDescriptorTransfer, []int{0} }

// Represents data transfer run state.
type TransferState int32

const (
	// State placeholder.
	TransferState_TRANSFER_STATE_UNSPECIFIED TransferState = 0
	// Data transfer is inactive.
	TransferState_INACTIVE TransferState = 1
	// Data transfer is scheduled and is waiting to be picked up by
	// data transfer backend.
	TransferState_PENDING TransferState = 2
	// Data transfer is in progress.
	TransferState_RUNNING TransferState = 3
	// Data transfer completed successsfully.
	TransferState_SUCCEEDED TransferState = 4
	// Data transfer failed.
	TransferState_FAILED TransferState = 5
	// Data transfer is cancelled.
	TransferState_CANCELLED TransferState = 6
)

var TransferState_name = map[int32]string{
	0: "TRANSFER_STATE_UNSPECIFIED",
	1: "INACTIVE",
	2: "PENDING",
	3: "RUNNING",
	4: "SUCCEEDED",
	5: "FAILED",
	6: "CANCELLED",
}
var TransferState_value = map[string]int32{
	"TRANSFER_STATE_UNSPECIFIED": 0,
	"INACTIVE":                   1,
	"PENDING":                    2,
	"RUNNING":                    3,
	"SUCCEEDED":                  4,
	"FAILED":                     5,
	"CANCELLED":                  6,
}

func (x TransferState) String() string {
	return proto.EnumName(TransferState_name, int32(x))
}
func (TransferState) EnumDescriptor() ([]byte, []int) { return fileDescriptorTransfer, []int{1} }

// Represents data transfer user facing message severity.
type TransferMessage_MessageSeverity int32

const (
	// No severity specified.
	TransferMessage_MESSAGE_SEVERITY_UNSPECIFIED TransferMessage_MessageSeverity = 0
	// Informational message.
	TransferMessage_INFO TransferMessage_MessageSeverity = 1
	// Warning message.
	TransferMessage_WARNING TransferMessage_MessageSeverity = 2
	// Error message.
	TransferMessage_ERROR TransferMessage_MessageSeverity = 3
)

var TransferMessage_MessageSeverity_name = map[int32]string{
	0: "MESSAGE_SEVERITY_UNSPECIFIED",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
}
var TransferMessage_MessageSeverity_value = map[string]int32{
	"MESSAGE_SEVERITY_UNSPECIFIED": 0,
	"INFO":    1,
	"WARNING": 2,
	"ERROR":   3,
}

func (x TransferMessage_MessageSeverity) String() string {
	return proto.EnumName(TransferMessage_MessageSeverity_name, int32(x))
}
func (TransferMessage_MessageSeverity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTransfer, []int{2, 0}
}

// Represents a data transfer configuration. A transfer configuration
// contains all metadata needed to perform a data transfer. For example,
// `destination_dataset_id` specifies where data should be stored.
// When a new transfer configuration is created, the specified
// `destination_dataset_id` is created when needed and shared with the
// appropriate data source service account.
type TransferConfig struct {
	// The resource name of the transfer config.
	// Transfer config names have the form
	// `projects/{project_id}/transferConfigs/{config_id}`.
	// Where `config_id` is usually a uuid, even though it is not
	// guaranteed or required. The name is ignored when creating a transfer
	// config.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The BigQuery target dataset id.
	DestinationDatasetId string `protobuf:"bytes,2,opt,name=destination_dataset_id,json=destinationDatasetId,proto3" json:"destination_dataset_id,omitempty"`
	// User specified display name for the data transfer.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Data source id. Cannot be changed once data transfer is created.
	DataSourceId string `protobuf:"bytes,5,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	// Data transfer specific parameters.
	Params *google_protobuf1.Struct `protobuf:"bytes,9,opt,name=params" json:"params,omitempty"`
	// Data transfer schedule.
	// If the data source does not support a custom schedule, this should be
	// empty. If it is empty, the default value for the data source will be
	// used.
	// The specified times are in UTC.
	// Examples of valid format:
	// `1st,3rd monday of month 15:30`,
	// `every wed,fri of jan,jun 13:15`, and
	// `first sunday of quarter 00:00`.
	// See more explanation about the format here:
	// https://cloud.google.com/appengine/docs/flexible/python/scheduling-jobs-with-cron-yaml#the_schedule_format
	// NOTE: the granularity should be at least 8 hours, or less frequent.
	Schedule string `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// The number of days to look back to automatically refresh the data.
	// For example, if `data_refresh_window_days = 10`, then every day
	// BigQuery reingests data for [today-10, today-1], rather than ingesting data
	// for just [today-1].
	// Only valid if the data source supports the feature. Set the value to  0
	// to use the default value.
	DataRefreshWindowDays int32 `protobuf:"varint,12,opt,name=data_refresh_window_days,json=dataRefreshWindowDays,proto3" json:"data_refresh_window_days,omitempty"`
	// Is this config disabled. When set to true, no runs are scheduled
	// for a given transfer.
	Disabled bool `protobuf:"varint,13,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Output only. Data transfer modification time. Ignored by server on input.
	UpdateTime *google_protobuf2.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	// Output only. Next time when data transfer will run.
	NextRunTime *google_protobuf2.Timestamp `protobuf:"bytes,8,opt,name=next_run_time,json=nextRunTime" json:"next_run_time,omitempty"`
	// Output only. State of the most recently updated transfer run.
	State TransferState `protobuf:"varint,10,opt,name=state,proto3,enum=google.cloud.bigquery.datatransfer.v1.TransferState" json:"state,omitempty"`
	// Output only. Unique ID of the user on whose behalf transfer is done.
	// Applicable only to data sources that do not support service accounts.
	// When set to 0, the data source service account credentials are used.
	UserId int64 `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Output only. Region in which BigQuery dataset is located.
	DatasetRegion string `protobuf:"bytes,14,opt,name=dataset_region,json=datasetRegion,proto3" json:"dataset_region,omitempty"`
}

func (m *TransferConfig) Reset()                    { *m = TransferConfig{} }
func (m *TransferConfig) String() string            { return proto.CompactTextString(m) }
func (*TransferConfig) ProtoMessage()               {}
func (*TransferConfig) Descriptor() ([]byte, []int) { return fileDescriptorTransfer, []int{0} }

func (m *TransferConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TransferConfig) GetDestinationDatasetId() string {
	if m != nil {
		return m.DestinationDatasetId
	}
	return ""
}

func (m *TransferConfig) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *TransferConfig) GetDataSourceId() string {
	if m != nil {
		return m.DataSourceId
	}
	return ""
}

func (m *TransferConfig) GetParams() *google_protobuf1.Struct {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *TransferConfig) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

func (m *TransferConfig) GetDataRefreshWindowDays() int32 {
	if m != nil {
		return m.DataRefreshWindowDays
	}
	return 0
}

func (m *TransferConfig) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *TransferConfig) GetUpdateTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *TransferConfig) GetNextRunTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.NextRunTime
	}
	return nil
}

func (m *TransferConfig) GetState() TransferState {
	if m != nil {
		return m.State
	}
	return TransferState_TRANSFER_STATE_UNSPECIFIED
}

func (m *TransferConfig) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TransferConfig) GetDatasetRegion() string {
	if m != nil {
		return m.DatasetRegion
	}
	return ""
}

// Represents a data transfer run.
// Next id: 23
type TransferRun struct {
	// The resource name of the transfer run.
	// Transfer run names have the form
	// `projects/{project_id}/locations/{location}/transferConfigs/{config_id}/runs/{run_id}`.
	// The name is ignored when creating a transfer run.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The BigQuery target dataset id.
	DestinationDatasetId string `protobuf:"bytes,2,opt,name=destination_dataset_id,json=destinationDatasetId,proto3" json:"destination_dataset_id,omitempty"`
	// Minimum time after which a transfer run can be started.
	ScheduleTime *google_protobuf2.Timestamp `protobuf:"bytes,3,opt,name=schedule_time,json=scheduleTime" json:"schedule_time,omitempty"`
	// Data transfer specific parameters.
	Params *google_protobuf1.Struct `protobuf:"bytes,9,opt,name=params" json:"params,omitempty"`
	// For batch transfer runs, specifies the date and time that
	// data should be ingested.
	RunTime *google_protobuf2.Timestamp `protobuf:"bytes,10,opt,name=run_time,json=runTime" json:"run_time,omitempty"`
	// Output only. Time when transfer run was started.
	// Parameter ignored by server for input requests.
	StartTime *google_protobuf2.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	// Output only. Time when transfer run ended.
	// Parameter ignored by server for input requests.
	EndTime *google_protobuf2.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	// Output only. Last time the data transfer run state was updated.
	UpdateTime *google_protobuf2.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	// Output only. Data source id.
	DataSourceId string `protobuf:"bytes,7,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	// Data transfer run state. Ignored for input requests.
	State TransferState `protobuf:"varint,8,opt,name=state,proto3,enum=google.cloud.bigquery.datatransfer.v1.TransferState" json:"state,omitempty"`
	// Output only. Unique ID of the user on whose behalf transfer is done.
	// Applicable only to data sources that do not support service accounts.
	// When set to 0, the data source service account credentials are used.
	// May be negative.
	UserId int64 `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Output only. Describes the schedule of this transfer run if it was
	// created as part of a regular schedule. For batch transfer runs that are
	// scheduled manually, this is empty.
	// NOTE: the system might choose to delay the schedule depending on the
	// current load, so `schedule_time` doesn't always matches this.
	Schedule string `protobuf:"bytes,12,opt,name=schedule,proto3" json:"schedule,omitempty"`
}

func (m *TransferRun) Reset()                    { *m = TransferRun{} }
func (m *TransferRun) String() string            { return proto.CompactTextString(m) }
func (*TransferRun) ProtoMessage()               {}
func (*TransferRun) Descriptor() ([]byte, []int) { return fileDescriptorTransfer, []int{1} }

func (m *TransferRun) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TransferRun) GetDestinationDatasetId() string {
	if m != nil {
		return m.DestinationDatasetId
	}
	return ""
}

func (m *TransferRun) GetScheduleTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.ScheduleTime
	}
	return nil
}

func (m *TransferRun) GetParams() *google_protobuf1.Struct {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *TransferRun) GetRunTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.RunTime
	}
	return nil
}

func (m *TransferRun) GetStartTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TransferRun) GetEndTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TransferRun) GetUpdateTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *TransferRun) GetDataSourceId() string {
	if m != nil {
		return m.DataSourceId
	}
	return ""
}

func (m *TransferRun) GetState() TransferState {
	if m != nil {
		return m.State
	}
	return TransferState_TRANSFER_STATE_UNSPECIFIED
}

func (m *TransferRun) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TransferRun) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

// Represents a user facing message for a particular data transfer run.
type TransferMessage struct {
	// Time when message was logged.
	MessageTime *google_protobuf2.Timestamp `protobuf:"bytes,1,opt,name=message_time,json=messageTime" json:"message_time,omitempty"`
	// Message severity.
	Severity TransferMessage_MessageSeverity `protobuf:"varint,2,opt,name=severity,proto3,enum=google.cloud.bigquery.datatransfer.v1.TransferMessage_MessageSeverity" json:"severity,omitempty"`
	// Message text.
	MessageText string `protobuf:"bytes,3,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
}

func (m *TransferMessage) Reset()                    { *m = TransferMessage{} }
func (m *TransferMessage) String() string            { return proto.CompactTextString(m) }
func (*TransferMessage) ProtoMessage()               {}
func (*TransferMessage) Descriptor() ([]byte, []int) { return fileDescriptorTransfer, []int{2} }

func (m *TransferMessage) GetMessageTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.MessageTime
	}
	return nil
}

func (m *TransferMessage) GetSeverity() TransferMessage_MessageSeverity {
	if m != nil {
		return m.Severity
	}
	return TransferMessage_MESSAGE_SEVERITY_UNSPECIFIED
}

func (m *TransferMessage) GetMessageText() string {
	if m != nil {
		return m.MessageText
	}
	return ""
}

func init() {
	proto.RegisterType((*TransferConfig)(nil), "google.cloud.bigquery.datatransfer.v1.TransferConfig")
	proto.RegisterType((*TransferRun)(nil), "google.cloud.bigquery.datatransfer.v1.TransferRun")
	proto.RegisterType((*TransferMessage)(nil), "google.cloud.bigquery.datatransfer.v1.TransferMessage")
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.TransferType", TransferType_name, TransferType_value)
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.TransferState", TransferState_name, TransferState_value)
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.TransferMessage_MessageSeverity", TransferMessage_MessageSeverity_name, TransferMessage_MessageSeverity_value)
}

func init() {
	proto.RegisterFile("google/cloud/bigquery/datatransfer/v1/transfer.proto", fileDescriptorTransfer)
}

var fileDescriptorTransfer = []byte{
	// 879 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0xf9, 0xcf, 0xc9, 0xcf, 0x46, 0x23, 0xa0, 0xa6, 0x5a, 0x20, 0x54, 0x54, 0x0a, 0x7b,
	0xe1, 0xa8, 0xa5, 0x2b, 0x84, 0x10, 0x20, 0xc7, 0x71, 0x82, 0xd1, 0xd6, 0x1b, 0xc6, 0x6e, 0x57,
	0x2b, 0x55, 0xb2, 0x26, 0xf1, 0x34, 0x6b, 0x29, 0xb1, 0x83, 0x67, 0xdc, 0x6d, 0x2e, 0x79, 0x07,
	0x9e, 0x80, 0x4b, 0x2e, 0x78, 0x10, 0x2e, 0xb8, 0xe4, 0x79, 0xd0, 0x8c, 0x7f, 0xd4, 0x4d, 0x91,
	0xd2, 0x4a, 0x70, 0x65, 0xcf, 0x39, 0xdf, 0xf7, 0xcd, 0x37, 0xe7, 0x9c, 0x19, 0x38, 0x5b, 0x46,
	0xd1, 0x72, 0x45, 0x87, 0x8b, 0x55, 0x94, 0xf8, 0xc3, 0x79, 0xb0, 0xfc, 0x39, 0xa1, 0xf1, 0x76,
	0xe8, 0x13, 0x4e, 0x78, 0x4c, 0x42, 0x76, 0x4d, 0xe3, 0xe1, 0xcd, 0xc9, 0x30, 0xff, 0xd7, 0x36,
	0x71, 0xc4, 0x23, 0x74, 0x9c, 0xb2, 0x34, 0xc9, 0xd2, 0x72, 0x96, 0x76, 0x97, 0xa5, 0xdd, 0x9c,
	0x1c, 0x3e, 0xcd, 0xc4, 0xc9, 0x26, 0x18, 0x92, 0x30, 0x8c, 0x38, 0xe1, 0x41, 0x14, 0xb2, 0x54,
	0xa4, 0xc8, 0xca, 0xd5, 0x3c, 0xb9, 0x1e, 0x32, 0x1e, 0x27, 0x0b, 0x9e, 0x65, 0x3f, 0xdd, 0xcd,
	0xf2, 0x60, 0x4d, 0x19, 0x27, 0xeb, 0x4d, 0x06, 0x38, 0xc8, 0x00, 0xf1, 0x66, 0x31, 0x64, 0x9c,
	0xf0, 0x24, 0xd3, 0x3d, 0xfa, 0xab, 0x02, 0x5d, 0x37, 0x73, 0x61, 0x44, 0xe1, 0x75, 0xb0, 0x44,
	0x08, 0x2a, 0x21, 0x59, 0x53, 0x55, 0xe9, 0x2b, 0x83, 0x26, 0x96, 0xff, 0xe8, 0x0c, 0x3e, 0xf4,
	0x29, 0xe3, 0x41, 0x28, 0x4d, 0x79, 0xc2, 0x3b, 0xa3, 0xdc, 0x0b, 0x7c, 0xb5, 0x24, 0x51, 0xef,
	0xdf, 0xc9, 0x8e, 0xd3, 0xa4, 0xe5, 0xa3, 0xcf, 0xa0, 0xed, 0x07, 0x6c, 0xb3, 0x22, 0x5b, 0x4f,
	0x2a, 0x96, 0x25, 0xb6, 0x95, 0xc5, 0x6c, 0x21, 0xfc, 0x39, 0x74, 0x85, 0x98, 0xc7, 0xa2, 0x24,
	0x5e, 0x50, 0x21, 0x58, 0x95, 0xa0, 0xb6, 0x88, 0x3a, 0x32, 0x68, 0xf9, 0x68, 0x08, 0xb5, 0x0d,
	0x89, 0xc9, 0x9a, 0xa9, 0xcd, 0xbe, 0x32, 0x68, 0x9d, 0x1e, 0x68, 0x59, 0x4d, 0xf3, 0x03, 0x6b,
	0x8e, 0x2c, 0x07, 0xce, 0x60, 0xe8, 0x10, 0x1a, 0x6c, 0xf1, 0x86, 0xfa, 0xc9, 0x8a, 0xaa, 0x75,
	0x29, 0x58, 0xac, 0xd1, 0x57, 0xa0, 0xca, 0x2d, 0x63, 0x7a, 0x1d, 0x53, 0xf6, 0xc6, 0x7b, 0x1b,
	0x84, 0x7e, 0xf4, 0xd6, 0xf3, 0xc9, 0x96, 0xa9, 0xed, 0xbe, 0x32, 0xa8, 0xe2, 0x0f, 0x44, 0x1e,
	0xa7, 0xe9, 0x57, 0x32, 0x3b, 0x26, 0x5b, 0x29, 0xea, 0x07, 0x8c, 0xcc, 0x57, 0xd4, 0x57, 0x3b,
	0x7d, 0x65, 0xd0, 0xc0, 0xc5, 0x1a, 0x7d, 0x03, 0xad, 0x64, 0xe3, 0x13, 0x4e, 0x3d, 0x51, 0x7a,
	0xb5, 0x22, 0x6d, 0x1e, 0xde, 0xb3, 0xe9, 0xe6, 0x7d, 0xc1, 0x90, 0xc2, 0x45, 0x00, 0x7d, 0x07,
	0x9d, 0x90, 0xde, 0x72, 0x2f, 0x4e, 0xc2, 0x94, 0xde, 0xd8, 0x4b, 0x6f, 0x09, 0x02, 0x4e, 0x42,
	0xc9, 0xff, 0x11, 0xaa, 0xa2, 0xa9, 0x54, 0x85, 0xbe, 0x32, 0xe8, 0x9e, 0x9e, 0x69, 0x0f, 0x9a,
	0x38, 0x2d, 0xef, 0xbb, 0x23, 0xb8, 0x38, 0x95, 0x40, 0x07, 0x50, 0x4f, 0x18, 0x8d, 0x45, 0x27,
	0x5a, 0x7d, 0x65, 0x50, 0xc6, 0x35, 0xb1, 0xb4, 0x7c, 0x74, 0x9c, 0x76, 0x4a, 0xb4, 0x3d, 0xa6,
	0xcb, 0x20, 0x0a, 0xd5, 0xae, 0x2c, 0x6c, 0x27, 0x8b, 0x62, 0x19, 0x3c, 0xfa, 0xbb, 0x02, 0xad,
	0x5c, 0x18, 0x27, 0xe1, 0x7f, 0x38, 0x4d, 0xdf, 0x43, 0x27, 0xef, 0x61, 0x5a, 0xa5, 0xf2, 0xde,
	0x2a, 0xb5, 0x73, 0x82, 0x2c, 0xd3, 0xa3, 0xa7, 0xe8, 0x39, 0x34, 0x8a, 0x96, 0xc0, 0xde, 0xcd,
	0xea, 0x71, 0xd6, 0x8e, 0xaf, 0x01, 0x18, 0x27, 0x31, 0x7f, 0xe8, 0x28, 0x34, 0x25, 0x5a, 0x52,
	0x9f, 0x43, 0x83, 0x86, 0x7e, 0x4a, 0xac, 0xee, 0xdf, 0x91, 0x86, 0xbe, 0xa4, 0xed, 0x4c, 0x5f,
	0xed, 0x51, 0xd3, 0x77, 0xff, 0x0a, 0xd6, 0xff, 0xe5, 0x0a, 0x16, 0x33, 0xd6, 0xf8, 0x1f, 0x67,
	0xec, 0xee, 0xb5, 0x6d, 0xbf, 0x7b, 0x6d, 0x8f, 0xfe, 0x28, 0xc1, 0x93, 0x5c, 0xed, 0x9c, 0x32,
	0x46, 0x96, 0x14, 0x7d, 0x0b, 0xed, 0x75, 0xfa, 0x9b, 0x1e, 0x5c, 0xd9, 0x7f, 0x6f, 0x32, 0xbc,
	0x3c, 0xf9, 0x1c, 0x1a, 0x8c, 0xde, 0xd0, 0x38, 0xe0, 0x5b, 0x39, 0x79, 0xdd, 0xd3, 0xc9, 0x23,
	0x8f, 0x95, 0x19, 0xd1, 0xb2, 0xaf, 0x93, 0xa9, 0xe1, 0x42, 0x57, 0xbc, 0x81, 0x85, 0x45, 0x7a,
	0xcb, 0xf3, 0x37, 0x30, 0xb7, 0x41, 0x6f, 0xf9, 0xd1, 0x05, 0x3c, 0xd9, 0xe1, 0xa3, 0x3e, 0x3c,
	0x3d, 0x37, 0x1d, 0x47, 0x9f, 0x9a, 0x9e, 0x63, 0x5e, 0x9a, 0xd8, 0x72, 0x5f, 0x7b, 0x17, 0xb6,
	0x33, 0x33, 0x0d, 0x6b, 0x62, 0x99, 0xe3, 0xde, 0x7b, 0xa8, 0x01, 0x15, 0xcb, 0x9e, 0xbc, 0xec,
	0x29, 0xa8, 0x05, 0xf5, 0x57, 0x3a, 0xb6, 0x2d, 0x7b, 0xda, 0x2b, 0xa1, 0x26, 0x54, 0x4d, 0x8c,
	0x5f, 0xe2, 0x5e, 0xf9, 0xd9, 0x14, 0xda, 0xb9, 0x4d, 0x77, 0xbb, 0xa1, 0xe8, 0x63, 0xf8, 0xc8,
	0xc5, 0xba, 0xed, 0x4c, 0x4c, 0xec, 0xb9, 0xaf, 0x67, 0xe6, 0x8e, 0x60, 0x13, 0xaa, 0x23, 0xdd,
	0x35, 0x7e, 0xe8, 0x29, 0xa8, 0x03, 0x4d, 0xc7, 0xc5, 0xa6, 0x7e, 0x2e, 0x35, 0x9f, 0xfd, 0xa2,
	0x40, 0xe7, 0x9d, 0x3e, 0xa2, 0x4f, 0xe0, 0xb0, 0x90, 0x72, 0x5c, 0xdd, 0xdd, 0xd5, 0x6a, 0x43,
	0xc3, 0xb2, 0x75, 0xc3, 0xb5, 0x2e, 0xcd, 0xd4, 0xe0, 0xcc, 0xb4, 0xc7, 0xa9, 0xc1, 0x16, 0xd4,
	0xf1, 0x85, 0x2d, 0xdd, 0x96, 0xe5, 0x46, 0x17, 0x86, 0x61, 0x9a, 0x63, 0x73, 0xdc, 0xab, 0x20,
	0x80, 0xda, 0x44, 0xb7, 0x5e, 0x98, 0xe3, 0x5e, 0x55, 0xa4, 0x0c, 0xdd, 0x36, 0xcc, 0x17, 0x62,
	0x59, 0x1b, 0xfd, 0xaa, 0xc0, 0x17, 0x8b, 0x68, 0xfd, 0xb0, 0xf6, 0x8c, 0x0a, 0xbb, 0x33, 0x31,
	0x01, 0x33, 0xe5, 0xb7, 0x52, 0x75, 0x6a, 0x8c, 0xc6, 0xee, 0xef, 0xa5, 0xe3, 0x69, 0x2a, 0x60,
	0x48, 0x81, 0x51, 0xb0, 0xfc, 0x49, 0x0a, 0x88, 0x57, 0x26, 0xe7, 0x68, 0x97, 0x27, 0x7f, 0xe6,
	0xb8, 0x2b, 0x89, 0xbb, 0xca, 0x71, 0x57, 0x77, 0x71, 0x57, 0x97, 0x27, 0xf3, 0x9a, 0x1c, 0xb1,
	0x2f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x46, 0x33, 0xbd, 0x1a, 0x08, 0x00, 0x00,
}
