// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/api/servicecontrol/v1/metric_value.proto

package google_api_servicecontrol_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "go.pedge.io/pb/go/google/api"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"
import _ "go.pedge.io/pb/go/google/type"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Represents a single metric value.
type MetricValue struct {
	// The labels describing the metric value.
	// See comments on [google.api.servicecontrol.v1.Operation.labels][google.api.servicecontrol.v1.Operation.labels] for
	// the overriding relationship.
	Labels map[string]string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The start of the time period over which this metric value's measurement
	// applies. The time period has different semantics for different metric
	// types (cumulative, delta, and gauge). See the metric definition
	// documentation in the service configuration for details.
	StartTime *google_protobuf3.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	// The end of the time period over which this metric value's measurement
	// applies.
	EndTime *google_protobuf3.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	// The value. The type of value used in the request must
	// agree with the metric definition in the service configuration, otherwise
	// the MetricValue is rejected.
	//
	// Types that are valid to be assigned to Value:
	//	*MetricValue_BoolValue
	//	*MetricValue_Int64Value
	//	*MetricValue_DoubleValue
	//	*MetricValue_StringValue
	//	*MetricValue_DistributionValue
	Value isMetricValue_Value `protobuf_oneof:"value"`
}

func (m *MetricValue) Reset()                    { *m = MetricValue{} }
func (m *MetricValue) String() string            { return proto.CompactTextString(m) }
func (*MetricValue) ProtoMessage()               {}
func (*MetricValue) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type isMetricValue_Value interface {
	isMetricValue_Value()
}

type MetricValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,oneof"`
}
type MetricValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,5,opt,name=int64_value,json=int64Value,oneof"`
}
type MetricValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,oneof"`
}
type MetricValue_StringValue struct {
	StringValue string `protobuf:"bytes,7,opt,name=string_value,json=stringValue,oneof"`
}
type MetricValue_DistributionValue struct {
	DistributionValue *Distribution `protobuf:"bytes,8,opt,name=distribution_value,json=distributionValue,oneof"`
}

func (*MetricValue_BoolValue) isMetricValue_Value()         {}
func (*MetricValue_Int64Value) isMetricValue_Value()        {}
func (*MetricValue_DoubleValue) isMetricValue_Value()       {}
func (*MetricValue_StringValue) isMetricValue_Value()       {}
func (*MetricValue_DistributionValue) isMetricValue_Value() {}

func (m *MetricValue) GetValue() isMetricValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MetricValue) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *MetricValue) GetStartTime() *google_protobuf3.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *MetricValue) GetEndTime() *google_protobuf3.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *MetricValue) GetBoolValue() bool {
	if x, ok := m.GetValue().(*MetricValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *MetricValue) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*MetricValue_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *MetricValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*MetricValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *MetricValue) GetStringValue() string {
	if x, ok := m.GetValue().(*MetricValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *MetricValue) GetDistributionValue() *Distribution {
	if x, ok := m.GetValue().(*MetricValue_DistributionValue); ok {
		return x.DistributionValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MetricValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MetricValue_OneofMarshaler, _MetricValue_OneofUnmarshaler, _MetricValue_OneofSizer, []interface{}{
		(*MetricValue_BoolValue)(nil),
		(*MetricValue_Int64Value)(nil),
		(*MetricValue_DoubleValue)(nil),
		(*MetricValue_StringValue)(nil),
		(*MetricValue_DistributionValue)(nil),
	}
}

func _MetricValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MetricValue)
	// value
	switch x := m.Value.(type) {
	case *MetricValue_BoolValue:
		t := uint64(0)
		if x.BoolValue {
			t = 1
		}
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *MetricValue_Int64Value:
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int64Value))
	case *MetricValue_DoubleValue:
		b.EncodeVarint(6<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *MetricValue_StringValue:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *MetricValue_DistributionValue:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DistributionValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MetricValue.Value has unexpected type %T", x)
	}
	return nil
}

func _MetricValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MetricValue)
	switch tag {
	case 4: // value.bool_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &MetricValue_BoolValue{x != 0}
		return true, err
	case 5: // value.int64_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &MetricValue_Int64Value{int64(x)}
		return true, err
	case 6: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &MetricValue_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 7: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &MetricValue_StringValue{x}
		return true, err
	case 8: // value.distribution_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Distribution)
		err := b.DecodeMessage(msg)
		m.Value = &MetricValue_DistributionValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MetricValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MetricValue)
	// value
	switch x := m.Value.(type) {
	case *MetricValue_BoolValue:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += 1
	case *MetricValue_Int64Value:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int64Value))
	case *MetricValue_DoubleValue:
		n += proto.SizeVarint(6<<3 | proto.WireFixed64)
		n += 8
	case *MetricValue_StringValue:
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *MetricValue_DistributionValue:
		s := proto.Size(x.DistributionValue)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Represents a set of metric values in the same metric.
// Each metric value in the set should have a unique combination of start time,
// end time, and label values.
type MetricValueSet struct {
	// The metric name defined in the service configuration.
	MetricName string `protobuf:"bytes,1,opt,name=metric_name,json=metricName" json:"metric_name,omitempty"`
	// The values in this metric.
	MetricValues []*MetricValue `protobuf:"bytes,2,rep,name=metric_values,json=metricValues" json:"metric_values,omitempty"`
}

func (m *MetricValueSet) Reset()                    { *m = MetricValueSet{} }
func (m *MetricValueSet) String() string            { return proto.CompactTextString(m) }
func (*MetricValueSet) ProtoMessage()               {}
func (*MetricValueSet) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *MetricValueSet) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *MetricValueSet) GetMetricValues() []*MetricValue {
	if m != nil {
		return m.MetricValues
	}
	return nil
}

func init() {
	proto.RegisterType((*MetricValue)(nil), "google.api.servicecontrol.v1.MetricValue")
	proto.RegisterType((*MetricValueSet)(nil), "google.api.servicecontrol.v1.MetricValueSet")
}

func init() { proto.RegisterFile("google/api/servicecontrol/v1/metric_value.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xb3, 0x31, 0xcd, 0xc7, 0xb8, 0x20, 0x58, 0x90, 0xb0, 0xa2, 0x4a, 0x31, 0xe5, 0x62,
	0x38, 0xd8, 0x6a, 0xa1, 0x88, 0x22, 0x4e, 0x11, 0x48, 0x39, 0xd0, 0xaa, 0x32, 0x88, 0x0b, 0x87,
	0x6a, 0x9d, 0x0c, 0xd1, 0x0a, 0x7b, 0xd7, 0xf2, 0x6e, 0x22, 0xe5, 0xc8, 0x7f, 0xcd, 0x05, 0x09,
	0xed, 0x47, 0x60, 0x73, 0x09, 0xbd, 0x79, 0xc6, 0xef, 0x37, 0xfb, 0x76, 0xe7, 0x41, 0xb1, 0x92,
	0x72, 0x55, 0x63, 0xc1, 0x5a, 0x5e, 0x28, 0xec, 0x36, 0x7c, 0x81, 0x0b, 0x29, 0x74, 0x27, 0xeb,
	0x62, 0x73, 0x56, 0x34, 0xa8, 0x3b, 0xbe, 0xb8, 0xdd, 0xb0, 0x7a, 0x8d, 0x79, 0xdb, 0x49, 0x2d,
	0xe9, 0x89, 0x03, 0x72, 0xd6, 0xf2, 0x7c, 0x1f, 0xc8, 0x37, 0x67, 0x93, 0x93, 0x60, 0x1c, 0x13,
	0x42, 0x6a, 0xa6, 0xb9, 0x14, 0xca, 0xb1, 0x93, 0xc3, 0x87, 0x2d, 0xb9, 0xd2, 0x1d, 0xaf, 0xd6,
	0x86, 0xf0, 0xc0, 0xd4, 0x03, 0xb6, 0xaa, 0xd6, 0xdf, 0x0b, 0xcd, 0x1b, 0x54, 0x9a, 0x35, 0xad,
	0x17, 0x3c, 0xf5, 0x02, 0xbd, 0x6d, 0xb1, 0x68, 0xa4, 0xc0, 0xad, 0xfb, 0x71, 0xfa, 0x3b, 0x82,
	0xf8, 0xca, 0xba, 0xff, 0x6a, 0xcc, 0xd3, 0x2b, 0x18, 0xd4, 0xac, 0xc2, 0x5a, 0x25, 0x24, 0x8d,
	0xb2, 0xf8, 0xfc, 0x22, 0x3f, 0x74, 0x8f, 0x3c, 0x40, 0xf3, 0x4f, 0x96, 0xfb, 0x28, 0x74, 0xb7,
	0x2d, 0xfd, 0x10, 0x7a, 0x09, 0xa0, 0x34, 0xeb, 0xf4, 0xad, 0x31, 0x94, 0xf4, 0x53, 0x92, 0xc5,
	0xe7, 0x93, 0xdd, 0xc8, 0x9d, 0xdb, 0xfc, 0xcb, 0xce, 0x6d, 0x39, 0xb6, 0x6a, 0x53, 0xd3, 0x0b,
	0x18, 0xa1, 0x58, 0x3a, 0x30, 0xfa, 0x2f, 0x38, 0x44, 0xb1, 0xb4, 0xd8, 0x14, 0xa0, 0x92, 0xb2,
	0x76, 0xbb, 0x48, 0xee, 0xa5, 0x24, 0x1b, 0xcd, 0x7b, 0xe5, 0xd8, 0xf4, 0xdc, 0x0d, 0x9f, 0x41,
	0xcc, 0x85, 0x7e, 0xf3, 0xda, 0x2b, 0x8e, 0x52, 0x92, 0x45, 0xf3, 0x5e, 0x09, 0xb6, 0xe9, 0x24,
	0xcf, 0xe1, 0x78, 0x29, 0xd7, 0x55, 0x8d, 0x5e, 0x33, 0x48, 0x49, 0x46, 0xe6, 0xbd, 0x32, 0x76,
	0xdd, 0xbf, 0x22, 0xb3, 0x07, 0xb1, 0xf2, 0xa2, 0x61, 0x4a, 0xb2, 0xb1, 0x11, 0xb9, 0xae, 0x13,
	0x7d, 0x03, 0x1a, 0xae, 0xcb, 0x4b, 0x47, 0xf6, 0x3a, 0x2f, 0x0f, 0x3f, 0xed, 0x87, 0x80, 0x9b,
	0xf7, 0xca, 0x47, 0xe1, 0x1c, 0x3b, 0x7c, 0x72, 0x09, 0x71, 0xf0, 0xe6, 0xf4, 0x21, 0x44, 0x3f,
	0x70, 0x9b, 0x10, 0xe3, 0xa3, 0x34, 0x9f, 0xf4, 0x09, 0x1c, 0xb9, 0x03, 0xfb, 0xb6, 0xe7, 0x8a,
	0x77, 0xfd, 0xb7, 0x64, 0x36, 0xf4, 0x7f, 0x4e, 0x7f, 0x12, 0x78, 0x10, 0x2c, 0xf1, 0x33, 0x6a,
	0x3a, 0x85, 0xd8, 0xe7, 0x59, 0xb0, 0x06, 0xfd, 0x3c, 0x70, 0xad, 0x6b, 0xd6, 0x20, 0xbd, 0x86,
	0xfb, 0x61, 0xe0, 0x55, 0xd2, 0xb7, 0x51, 0x79, 0x71, 0xe7, 0xa8, 0x94, 0xc7, 0xcd, 0xbf, 0x42,
	0xcd, 0xde, 0x43, 0xba, 0x90, 0xcd, 0x41, 0x7a, 0xf6, 0x78, 0xdf, 0xe4, 0x8d, 0x49, 0xc0, 0x0d,
	0xf9, 0x45, 0x48, 0x35, 0xb0, 0x69, 0x78, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xcd, 0xe1,
	0xe7, 0xa2, 0x03, 0x00, 0x00,
}
