// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/vision/v1p1beta1/image_annotator.proto

package google_cloud_vision_v1p1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "go.pedge.io/pb/go/google/api"
import google_rpc "go.pedge.io/pb/go/google/rpc"
import google_type "go.pedge.io/pb/go/google/type"
import google_type1 "go.pedge.io/pb/go/google/type"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A bucketized representation of likelihood, which is intended to give clients
// highly stable results across model upgrades.
type Likelihood int32

const (
	// Unknown likelihood.
	Likelihood_UNKNOWN Likelihood = 0
	// It is very unlikely that the image belongs to the specified vertical.
	Likelihood_VERY_UNLIKELY Likelihood = 1
	// It is unlikely that the image belongs to the specified vertical.
	Likelihood_UNLIKELY Likelihood = 2
	// It is possible that the image belongs to the specified vertical.
	Likelihood_POSSIBLE Likelihood = 3
	// It is likely that the image belongs to the specified vertical.
	Likelihood_LIKELY Likelihood = 4
	// It is very likely that the image belongs to the specified vertical.
	Likelihood_VERY_LIKELY Likelihood = 5
)

var Likelihood_name = map[int32]string{
	0: "UNKNOWN",
	1: "VERY_UNLIKELY",
	2: "UNLIKELY",
	3: "POSSIBLE",
	4: "LIKELY",
	5: "VERY_LIKELY",
}
var Likelihood_value = map[string]int32{
	"UNKNOWN":       0,
	"VERY_UNLIKELY": 1,
	"UNLIKELY":      2,
	"POSSIBLE":      3,
	"LIKELY":        4,
	"VERY_LIKELY":   5,
}

func (x Likelihood) String() string {
	return proto.EnumName(Likelihood_name, int32(x))
}
func (Likelihood) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// Type of image feature.
type Feature_Type int32

const (
	// Unspecified feature type.
	Feature_TYPE_UNSPECIFIED Feature_Type = 0
	// Run face detection.
	Feature_FACE_DETECTION Feature_Type = 1
	// Run landmark detection.
	Feature_LANDMARK_DETECTION Feature_Type = 2
	// Run logo detection.
	Feature_LOGO_DETECTION Feature_Type = 3
	// Run label detection.
	Feature_LABEL_DETECTION Feature_Type = 4
	// Run OCR.
	Feature_TEXT_DETECTION Feature_Type = 5
	// Run dense text document OCR. Takes precedence when both
	// DOCUMENT_TEXT_DETECTION and TEXT_DETECTION are present.
	Feature_DOCUMENT_TEXT_DETECTION Feature_Type = 11
	// Run computer vision models to compute image safe-search properties.
	Feature_SAFE_SEARCH_DETECTION Feature_Type = 6
	// Compute a set of image properties, such as the image's dominant colors.
	Feature_IMAGE_PROPERTIES Feature_Type = 7
	// Run crop hints.
	Feature_CROP_HINTS Feature_Type = 9
	// Run web detection.
	Feature_WEB_DETECTION Feature_Type = 10
)

var Feature_Type_name = map[int32]string{
	0:  "TYPE_UNSPECIFIED",
	1:  "FACE_DETECTION",
	2:  "LANDMARK_DETECTION",
	3:  "LOGO_DETECTION",
	4:  "LABEL_DETECTION",
	5:  "TEXT_DETECTION",
	11: "DOCUMENT_TEXT_DETECTION",
	6:  "SAFE_SEARCH_DETECTION",
	7:  "IMAGE_PROPERTIES",
	9:  "CROP_HINTS",
	10: "WEB_DETECTION",
}
var Feature_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED":        0,
	"FACE_DETECTION":          1,
	"LANDMARK_DETECTION":      2,
	"LOGO_DETECTION":          3,
	"LABEL_DETECTION":         4,
	"TEXT_DETECTION":          5,
	"DOCUMENT_TEXT_DETECTION": 11,
	"SAFE_SEARCH_DETECTION":   6,
	"IMAGE_PROPERTIES":        7,
	"CROP_HINTS":              9,
	"WEB_DETECTION":           10,
}

func (x Feature_Type) String() string {
	return proto.EnumName(Feature_Type_name, int32(x))
}
func (Feature_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

// Face landmark (feature) type.
// Left and right are defined from the vantage of the viewer of the image
// without considering mirror projections typical of photos. So, `LEFT_EYE`,
// typically, is the person's right eye.
type FaceAnnotation_Landmark_Type int32

const (
	// Unknown face landmark detected. Should not be filled.
	FaceAnnotation_Landmark_UNKNOWN_LANDMARK FaceAnnotation_Landmark_Type = 0
	// Left eye.
	FaceAnnotation_Landmark_LEFT_EYE FaceAnnotation_Landmark_Type = 1
	// Right eye.
	FaceAnnotation_Landmark_RIGHT_EYE FaceAnnotation_Landmark_Type = 2
	// Left of left eyebrow.
	FaceAnnotation_Landmark_LEFT_OF_LEFT_EYEBROW FaceAnnotation_Landmark_Type = 3
	// Right of left eyebrow.
	FaceAnnotation_Landmark_RIGHT_OF_LEFT_EYEBROW FaceAnnotation_Landmark_Type = 4
	// Left of right eyebrow.
	FaceAnnotation_Landmark_LEFT_OF_RIGHT_EYEBROW FaceAnnotation_Landmark_Type = 5
	// Right of right eyebrow.
	FaceAnnotation_Landmark_RIGHT_OF_RIGHT_EYEBROW FaceAnnotation_Landmark_Type = 6
	// Midpoint between eyes.
	FaceAnnotation_Landmark_MIDPOINT_BETWEEN_EYES FaceAnnotation_Landmark_Type = 7
	// Nose tip.
	FaceAnnotation_Landmark_NOSE_TIP FaceAnnotation_Landmark_Type = 8
	// Upper lip.
	FaceAnnotation_Landmark_UPPER_LIP FaceAnnotation_Landmark_Type = 9
	// Lower lip.
	FaceAnnotation_Landmark_LOWER_LIP FaceAnnotation_Landmark_Type = 10
	// Mouth left.
	FaceAnnotation_Landmark_MOUTH_LEFT FaceAnnotation_Landmark_Type = 11
	// Mouth right.
	FaceAnnotation_Landmark_MOUTH_RIGHT FaceAnnotation_Landmark_Type = 12
	// Mouth center.
	FaceAnnotation_Landmark_MOUTH_CENTER FaceAnnotation_Landmark_Type = 13
	// Nose, bottom right.
	FaceAnnotation_Landmark_NOSE_BOTTOM_RIGHT FaceAnnotation_Landmark_Type = 14
	// Nose, bottom left.
	FaceAnnotation_Landmark_NOSE_BOTTOM_LEFT FaceAnnotation_Landmark_Type = 15
	// Nose, bottom center.
	FaceAnnotation_Landmark_NOSE_BOTTOM_CENTER FaceAnnotation_Landmark_Type = 16
	// Left eye, top boundary.
	FaceAnnotation_Landmark_LEFT_EYE_TOP_BOUNDARY FaceAnnotation_Landmark_Type = 17
	// Left eye, right corner.
	FaceAnnotation_Landmark_LEFT_EYE_RIGHT_CORNER FaceAnnotation_Landmark_Type = 18
	// Left eye, bottom boundary.
	FaceAnnotation_Landmark_LEFT_EYE_BOTTOM_BOUNDARY FaceAnnotation_Landmark_Type = 19
	// Left eye, left corner.
	FaceAnnotation_Landmark_LEFT_EYE_LEFT_CORNER FaceAnnotation_Landmark_Type = 20
	// Right eye, top boundary.
	FaceAnnotation_Landmark_RIGHT_EYE_TOP_BOUNDARY FaceAnnotation_Landmark_Type = 21
	// Right eye, right corner.
	FaceAnnotation_Landmark_RIGHT_EYE_RIGHT_CORNER FaceAnnotation_Landmark_Type = 22
	// Right eye, bottom boundary.
	FaceAnnotation_Landmark_RIGHT_EYE_BOTTOM_BOUNDARY FaceAnnotation_Landmark_Type = 23
	// Right eye, left corner.
	FaceAnnotation_Landmark_RIGHT_EYE_LEFT_CORNER FaceAnnotation_Landmark_Type = 24
	// Left eyebrow, upper midpoint.
	FaceAnnotation_Landmark_LEFT_EYEBROW_UPPER_MIDPOINT FaceAnnotation_Landmark_Type = 25
	// Right eyebrow, upper midpoint.
	FaceAnnotation_Landmark_RIGHT_EYEBROW_UPPER_MIDPOINT FaceAnnotation_Landmark_Type = 26
	// Left ear tragion.
	FaceAnnotation_Landmark_LEFT_EAR_TRAGION FaceAnnotation_Landmark_Type = 27
	// Right ear tragion.
	FaceAnnotation_Landmark_RIGHT_EAR_TRAGION FaceAnnotation_Landmark_Type = 28
	// Left eye pupil.
	FaceAnnotation_Landmark_LEFT_EYE_PUPIL FaceAnnotation_Landmark_Type = 29
	// Right eye pupil.
	FaceAnnotation_Landmark_RIGHT_EYE_PUPIL FaceAnnotation_Landmark_Type = 30
	// Forehead glabella.
	FaceAnnotation_Landmark_FOREHEAD_GLABELLA FaceAnnotation_Landmark_Type = 31
	// Chin gnathion.
	FaceAnnotation_Landmark_CHIN_GNATHION FaceAnnotation_Landmark_Type = 32
	// Chin left gonion.
	FaceAnnotation_Landmark_CHIN_LEFT_GONION FaceAnnotation_Landmark_Type = 33
	// Chin right gonion.
	FaceAnnotation_Landmark_CHIN_RIGHT_GONION FaceAnnotation_Landmark_Type = 34
)

var FaceAnnotation_Landmark_Type_name = map[int32]string{
	0:  "UNKNOWN_LANDMARK",
	1:  "LEFT_EYE",
	2:  "RIGHT_EYE",
	3:  "LEFT_OF_LEFT_EYEBROW",
	4:  "RIGHT_OF_LEFT_EYEBROW",
	5:  "LEFT_OF_RIGHT_EYEBROW",
	6:  "RIGHT_OF_RIGHT_EYEBROW",
	7:  "MIDPOINT_BETWEEN_EYES",
	8:  "NOSE_TIP",
	9:  "UPPER_LIP",
	10: "LOWER_LIP",
	11: "MOUTH_LEFT",
	12: "MOUTH_RIGHT",
	13: "MOUTH_CENTER",
	14: "NOSE_BOTTOM_RIGHT",
	15: "NOSE_BOTTOM_LEFT",
	16: "NOSE_BOTTOM_CENTER",
	17: "LEFT_EYE_TOP_BOUNDARY",
	18: "LEFT_EYE_RIGHT_CORNER",
	19: "LEFT_EYE_BOTTOM_BOUNDARY",
	20: "LEFT_EYE_LEFT_CORNER",
	21: "RIGHT_EYE_TOP_BOUNDARY",
	22: "RIGHT_EYE_RIGHT_CORNER",
	23: "RIGHT_EYE_BOTTOM_BOUNDARY",
	24: "RIGHT_EYE_LEFT_CORNER",
	25: "LEFT_EYEBROW_UPPER_MIDPOINT",
	26: "RIGHT_EYEBROW_UPPER_MIDPOINT",
	27: "LEFT_EAR_TRAGION",
	28: "RIGHT_EAR_TRAGION",
	29: "LEFT_EYE_PUPIL",
	30: "RIGHT_EYE_PUPIL",
	31: "FOREHEAD_GLABELLA",
	32: "CHIN_GNATHION",
	33: "CHIN_LEFT_GONION",
	34: "CHIN_RIGHT_GONION",
}
var FaceAnnotation_Landmark_Type_value = map[string]int32{
	"UNKNOWN_LANDMARK":             0,
	"LEFT_EYE":                     1,
	"RIGHT_EYE":                    2,
	"LEFT_OF_LEFT_EYEBROW":         3,
	"RIGHT_OF_LEFT_EYEBROW":        4,
	"LEFT_OF_RIGHT_EYEBROW":        5,
	"RIGHT_OF_RIGHT_EYEBROW":       6,
	"MIDPOINT_BETWEEN_EYES":        7,
	"NOSE_TIP":                     8,
	"UPPER_LIP":                    9,
	"LOWER_LIP":                    10,
	"MOUTH_LEFT":                   11,
	"MOUTH_RIGHT":                  12,
	"MOUTH_CENTER":                 13,
	"NOSE_BOTTOM_RIGHT":            14,
	"NOSE_BOTTOM_LEFT":             15,
	"NOSE_BOTTOM_CENTER":           16,
	"LEFT_EYE_TOP_BOUNDARY":        17,
	"LEFT_EYE_RIGHT_CORNER":        18,
	"LEFT_EYE_BOTTOM_BOUNDARY":     19,
	"LEFT_EYE_LEFT_CORNER":         20,
	"RIGHT_EYE_TOP_BOUNDARY":       21,
	"RIGHT_EYE_RIGHT_CORNER":       22,
	"RIGHT_EYE_BOTTOM_BOUNDARY":    23,
	"RIGHT_EYE_LEFT_CORNER":        24,
	"LEFT_EYEBROW_UPPER_MIDPOINT":  25,
	"RIGHT_EYEBROW_UPPER_MIDPOINT": 26,
	"LEFT_EAR_TRAGION":             27,
	"RIGHT_EAR_TRAGION":            28,
	"LEFT_EYE_PUPIL":               29,
	"RIGHT_EYE_PUPIL":              30,
	"FOREHEAD_GLABELLA":            31,
	"CHIN_GNATHION":                32,
	"CHIN_LEFT_GONION":             33,
	"CHIN_RIGHT_GONION":            34,
}

func (x FaceAnnotation_Landmark_Type) String() string {
	return proto.EnumName(FaceAnnotation_Landmark_Type_name, int32(x))
}
func (FaceAnnotation_Landmark_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 0, 0}
}

// Users describe the type of Google Cloud Vision API tasks to perform over
// images by using *Feature*s. Each Feature indicates a type of image
// detection task to perform. Features encode the Cloud Vision API
// vertical to operate on and the number of top-scoring results to return.
type Feature struct {
	// The feature type.
	Type Feature_Type `protobuf:"varint,1,opt,name=type,enum=google.cloud.vision.v1p1beta1.Feature_Type" json:"type,omitempty"`
	// Maximum number of results of this type.
	MaxResults int32 `protobuf:"varint,2,opt,name=max_results,json=maxResults" json:"max_results,omitempty"`
	// Model to use for the feature.
	// Supported values: "builtin/stable" (the default if unset) and
	// "builtin/latest".
	Model string `protobuf:"bytes,3,opt,name=model" json:"model,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Feature) GetType() Feature_Type {
	if m != nil {
		return m.Type
	}
	return Feature_TYPE_UNSPECIFIED
}

func (m *Feature) GetMaxResults() int32 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

func (m *Feature) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

// External image source (Google Cloud Storage image location).
type ImageSource struct {
	// NOTE: For new code `image_uri` below is preferred.
	// Google Cloud Storage image URI, which must be in the following form:
	// `gs://bucket_name/object_name` (for details, see
	// [Google Cloud Storage Request
	// URIs](https://cloud.google.com/storage/docs/reference-uris)).
	// NOTE: Cloud Storage object versioning is not supported.
	GcsImageUri string `protobuf:"bytes,1,opt,name=gcs_image_uri,json=gcsImageUri" json:"gcs_image_uri,omitempty"`
	// Image URI which supports:
	// 1) Google Cloud Storage image URI, which must be in the following form:
	// `gs://bucket_name/object_name` (for details, see
	// [Google Cloud Storage Request
	// URIs](https://cloud.google.com/storage/docs/reference-uris)).
	// NOTE: Cloud Storage object versioning is not supported.
	// 2) Publicly accessible image HTTP/HTTPS URL.
	// This is preferred over the legacy `gcs_image_uri` above. When both
	// `gcs_image_uri` and `image_uri` are specified, `image_uri` takes
	// precedence.
	ImageUri string `protobuf:"bytes,2,opt,name=image_uri,json=imageUri" json:"image_uri,omitempty"`
}

func (m *ImageSource) Reset()                    { *m = ImageSource{} }
func (m *ImageSource) String() string            { return proto.CompactTextString(m) }
func (*ImageSource) ProtoMessage()               {}
func (*ImageSource) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ImageSource) GetGcsImageUri() string {
	if m != nil {
		return m.GcsImageUri
	}
	return ""
}

func (m *ImageSource) GetImageUri() string {
	if m != nil {
		return m.ImageUri
	}
	return ""
}

// Client image to perform Google Cloud Vision API tasks over.
type Image struct {
	// Image content, represented as a stream of bytes.
	// Note: as with all `bytes` fields, protobuffers use a pure binary
	// representation, whereas JSON representations use base64.
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Google Cloud Storage image location. If both `content` and `source`
	// are provided for an image, `content` takes precedence and is
	// used to perform the image annotation request.
	Source *ImageSource `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Image) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Image) GetSource() *ImageSource {
	if m != nil {
		return m.Source
	}
	return nil
}

// A face annotation object contains the results of face detection.
type FaceAnnotation struct {
	// The bounding polygon around the face. The coordinates of the bounding box
	// are in the original image's scale, as returned in `ImageParams`.
	// The bounding box is computed to "frame" the face in accordance with human
	// expectations. It is based on the landmarker results.
	// Note that one or more x and/or y coordinates may not be generated in the
	// `BoundingPoly` (the polygon will be unbounded) if only a partial face
	// appears in the image to be annotated.
	BoundingPoly *BoundingPoly `protobuf:"bytes,1,opt,name=bounding_poly,json=boundingPoly" json:"bounding_poly,omitempty"`
	// The `fd_bounding_poly` bounding polygon is tighter than the
	// `boundingPoly`, and encloses only the skin part of the face. Typically, it
	// is used to eliminate the face from any image analysis that detects the
	// "amount of skin" visible in an image. It is not based on the
	// landmarker results, only on the initial face detection, hence
	// the <code>fd</code> (face detection) prefix.
	FdBoundingPoly *BoundingPoly `protobuf:"bytes,2,opt,name=fd_bounding_poly,json=fdBoundingPoly" json:"fd_bounding_poly,omitempty"`
	// Detected face landmarks.
	Landmarks []*FaceAnnotation_Landmark `protobuf:"bytes,3,rep,name=landmarks" json:"landmarks,omitempty"`
	// Roll angle, which indicates the amount of clockwise/anti-clockwise rotation
	// of the face relative to the image vertical about the axis perpendicular to
	// the face. Range [-180,180].
	RollAngle float32 `protobuf:"fixed32,4,opt,name=roll_angle,json=rollAngle" json:"roll_angle,omitempty"`
	// Yaw angle, which indicates the leftward/rightward angle that the face is
	// pointing relative to the vertical plane perpendicular to the image. Range
	// [-180,180].
	PanAngle float32 `protobuf:"fixed32,5,opt,name=pan_angle,json=panAngle" json:"pan_angle,omitempty"`
	// Pitch angle, which indicates the upwards/downwards angle that the face is
	// pointing relative to the image's horizontal plane. Range [-180,180].
	TiltAngle float32 `protobuf:"fixed32,6,opt,name=tilt_angle,json=tiltAngle" json:"tilt_angle,omitempty"`
	// Detection confidence. Range [0, 1].
	DetectionConfidence float32 `protobuf:"fixed32,7,opt,name=detection_confidence,json=detectionConfidence" json:"detection_confidence,omitempty"`
	// Face landmarking confidence. Range [0, 1].
	LandmarkingConfidence float32 `protobuf:"fixed32,8,opt,name=landmarking_confidence,json=landmarkingConfidence" json:"landmarking_confidence,omitempty"`
	// Joy likelihood.
	JoyLikelihood Likelihood `protobuf:"varint,9,opt,name=joy_likelihood,json=joyLikelihood,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"joy_likelihood,omitempty"`
	// Sorrow likelihood.
	SorrowLikelihood Likelihood `protobuf:"varint,10,opt,name=sorrow_likelihood,json=sorrowLikelihood,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"sorrow_likelihood,omitempty"`
	// Anger likelihood.
	AngerLikelihood Likelihood `protobuf:"varint,11,opt,name=anger_likelihood,json=angerLikelihood,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"anger_likelihood,omitempty"`
	// Surprise likelihood.
	SurpriseLikelihood Likelihood `protobuf:"varint,12,opt,name=surprise_likelihood,json=surpriseLikelihood,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"surprise_likelihood,omitempty"`
	// Under-exposed likelihood.
	UnderExposedLikelihood Likelihood `protobuf:"varint,13,opt,name=under_exposed_likelihood,json=underExposedLikelihood,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"under_exposed_likelihood,omitempty"`
	// Blurred likelihood.
	BlurredLikelihood Likelihood `protobuf:"varint,14,opt,name=blurred_likelihood,json=blurredLikelihood,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"blurred_likelihood,omitempty"`
	// Headwear likelihood.
	HeadwearLikelihood Likelihood `protobuf:"varint,15,opt,name=headwear_likelihood,json=headwearLikelihood,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"headwear_likelihood,omitempty"`
}

func (m *FaceAnnotation) Reset()                    { *m = FaceAnnotation{} }
func (m *FaceAnnotation) String() string            { return proto.CompactTextString(m) }
func (*FaceAnnotation) ProtoMessage()               {}
func (*FaceAnnotation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *FaceAnnotation) GetBoundingPoly() *BoundingPoly {
	if m != nil {
		return m.BoundingPoly
	}
	return nil
}

func (m *FaceAnnotation) GetFdBoundingPoly() *BoundingPoly {
	if m != nil {
		return m.FdBoundingPoly
	}
	return nil
}

func (m *FaceAnnotation) GetLandmarks() []*FaceAnnotation_Landmark {
	if m != nil {
		return m.Landmarks
	}
	return nil
}

func (m *FaceAnnotation) GetRollAngle() float32 {
	if m != nil {
		return m.RollAngle
	}
	return 0
}

func (m *FaceAnnotation) GetPanAngle() float32 {
	if m != nil {
		return m.PanAngle
	}
	return 0
}

func (m *FaceAnnotation) GetTiltAngle() float32 {
	if m != nil {
		return m.TiltAngle
	}
	return 0
}

func (m *FaceAnnotation) GetDetectionConfidence() float32 {
	if m != nil {
		return m.DetectionConfidence
	}
	return 0
}

func (m *FaceAnnotation) GetLandmarkingConfidence() float32 {
	if m != nil {
		return m.LandmarkingConfidence
	}
	return 0
}

func (m *FaceAnnotation) GetJoyLikelihood() Likelihood {
	if m != nil {
		return m.JoyLikelihood
	}
	return Likelihood_UNKNOWN
}

func (m *FaceAnnotation) GetSorrowLikelihood() Likelihood {
	if m != nil {
		return m.SorrowLikelihood
	}
	return Likelihood_UNKNOWN
}

func (m *FaceAnnotation) GetAngerLikelihood() Likelihood {
	if m != nil {
		return m.AngerLikelihood
	}
	return Likelihood_UNKNOWN
}

func (m *FaceAnnotation) GetSurpriseLikelihood() Likelihood {
	if m != nil {
		return m.SurpriseLikelihood
	}
	return Likelihood_UNKNOWN
}

func (m *FaceAnnotation) GetUnderExposedLikelihood() Likelihood {
	if m != nil {
		return m.UnderExposedLikelihood
	}
	return Likelihood_UNKNOWN
}

func (m *FaceAnnotation) GetBlurredLikelihood() Likelihood {
	if m != nil {
		return m.BlurredLikelihood
	}
	return Likelihood_UNKNOWN
}

func (m *FaceAnnotation) GetHeadwearLikelihood() Likelihood {
	if m != nil {
		return m.HeadwearLikelihood
	}
	return Likelihood_UNKNOWN
}

// A face-specific landmark (for example, a face feature).
type FaceAnnotation_Landmark struct {
	// Face landmark type.
	Type FaceAnnotation_Landmark_Type `protobuf:"varint,3,opt,name=type,enum=google.cloud.vision.v1p1beta1.FaceAnnotation_Landmark_Type" json:"type,omitempty"`
	// Face landmark position.
	Position *Position `protobuf:"bytes,4,opt,name=position" json:"position,omitempty"`
}

func (m *FaceAnnotation_Landmark) Reset()                    { *m = FaceAnnotation_Landmark{} }
func (m *FaceAnnotation_Landmark) String() string            { return proto.CompactTextString(m) }
func (*FaceAnnotation_Landmark) ProtoMessage()               {}
func (*FaceAnnotation_Landmark) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

func (m *FaceAnnotation_Landmark) GetType() FaceAnnotation_Landmark_Type {
	if m != nil {
		return m.Type
	}
	return FaceAnnotation_Landmark_UNKNOWN_LANDMARK
}

func (m *FaceAnnotation_Landmark) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

// Detected entity location information.
type LocationInfo struct {
	// lat/long location coordinates.
	LatLng *google_type1.LatLng `protobuf:"bytes,1,opt,name=lat_lng,json=latLng" json:"lat_lng,omitempty"`
}

func (m *LocationInfo) Reset()                    { *m = LocationInfo{} }
func (m *LocationInfo) String() string            { return proto.CompactTextString(m) }
func (*LocationInfo) ProtoMessage()               {}
func (*LocationInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *LocationInfo) GetLatLng() *google_type1.LatLng {
	if m != nil {
		return m.LatLng
	}
	return nil
}

// A `Property` consists of a user-supplied name/value pair.
type Property struct {
	// Name of the property.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Value of the property.
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	// Value of numeric properties.
	Uint64Value uint64 `protobuf:"varint,3,opt,name=uint64_value,json=uint64Value" json:"uint64_value,omitempty"`
}

func (m *Property) Reset()                    { *m = Property{} }
func (m *Property) String() string            { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()               {}
func (*Property) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Property) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Property) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

// Set of detected entity features.
type EntityAnnotation struct {
	// Opaque entity ID. Some IDs may be available in
	// [Google Knowledge Graph Search API](https://developers.google.com/knowledge-graph/).
	Mid string `protobuf:"bytes,1,opt,name=mid" json:"mid,omitempty"`
	// The language code for the locale in which the entity textual
	// `description` is expressed.
	Locale string `protobuf:"bytes,2,opt,name=locale" json:"locale,omitempty"`
	// Entity textual description, expressed in its `locale` language.
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// Overall score of the result. Range [0, 1].
	Score float32 `protobuf:"fixed32,4,opt,name=score" json:"score,omitempty"`
	// The accuracy of the entity detection in an image.
	// For example, for an image in which the "Eiffel Tower" entity is detected,
	// this field represents the confidence that there is a tower in the query
	// image. Range [0, 1].
	Confidence float32 `protobuf:"fixed32,5,opt,name=confidence" json:"confidence,omitempty"`
	// The relevancy of the ICA (Image Content Annotation) label to the
	// image. For example, the relevancy of "tower" is likely higher to an image
	// containing the detected "Eiffel Tower" than to an image containing a
	// detected distant towering building, even though the confidence that
	// there is a tower in each image may be the same. Range [0, 1].
	Topicality float32 `protobuf:"fixed32,6,opt,name=topicality" json:"topicality,omitempty"`
	// Image region to which this entity belongs. Not produced
	// for `LABEL_DETECTION` features.
	BoundingPoly *BoundingPoly `protobuf:"bytes,7,opt,name=bounding_poly,json=boundingPoly" json:"bounding_poly,omitempty"`
	// The location information for the detected entity. Multiple
	// `LocationInfo` elements can be present because one location may
	// indicate the location of the scene in the image, and another location
	// may indicate the location of the place where the image was taken.
	// Location information is usually present for landmarks.
	Locations []*LocationInfo `protobuf:"bytes,8,rep,name=locations" json:"locations,omitempty"`
	// Some entities may have optional user-supplied `Property` (name/value)
	// fields, such a score or string that qualifies the entity.
	Properties []*Property `protobuf:"bytes,9,rep,name=properties" json:"properties,omitempty"`
}

func (m *EntityAnnotation) Reset()                    { *m = EntityAnnotation{} }
func (m *EntityAnnotation) String() string            { return proto.CompactTextString(m) }
func (*EntityAnnotation) ProtoMessage()               {}
func (*EntityAnnotation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *EntityAnnotation) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *EntityAnnotation) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *EntityAnnotation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EntityAnnotation) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *EntityAnnotation) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *EntityAnnotation) GetTopicality() float32 {
	if m != nil {
		return m.Topicality
	}
	return 0
}

func (m *EntityAnnotation) GetBoundingPoly() *BoundingPoly {
	if m != nil {
		return m.BoundingPoly
	}
	return nil
}

func (m *EntityAnnotation) GetLocations() []*LocationInfo {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *EntityAnnotation) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

// Set of features pertaining to the image, computed by computer vision
// methods over safe-search verticals (for example, adult, spoof, medical,
// violence).
type SafeSearchAnnotation struct {
	// Represents the adult content likelihood for the image. Adult content may
	// contain elements such as nudity, pornographic images or cartoons, or
	// sexual activities.
	Adult Likelihood `protobuf:"varint,1,opt,name=adult,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"adult,omitempty"`
	// Spoof likelihood. The likelihood that an modification
	// was made to the image's canonical version to make it appear
	// funny or offensive.
	Spoof Likelihood `protobuf:"varint,2,opt,name=spoof,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"spoof,omitempty"`
	// Likelihood that this is a medical image.
	Medical Likelihood `protobuf:"varint,3,opt,name=medical,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"medical,omitempty"`
	// Likelihood that this image contains violent content.
	Violence Likelihood `protobuf:"varint,4,opt,name=violence,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"violence,omitempty"`
	// Likelihood that the request image contains racy content. Racy content may
	// include (but is not limited to) skimpy or sheer clothing, strategically
	// covered nudity, lewd or provocative poses, or close-ups of sensitive
	// body areas.
	Racy Likelihood `protobuf:"varint,9,opt,name=racy,enum=google.cloud.vision.v1p1beta1.Likelihood" json:"racy,omitempty"`
}

func (m *SafeSearchAnnotation) Reset()                    { *m = SafeSearchAnnotation{} }
func (m *SafeSearchAnnotation) String() string            { return proto.CompactTextString(m) }
func (*SafeSearchAnnotation) ProtoMessage()               {}
func (*SafeSearchAnnotation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *SafeSearchAnnotation) GetAdult() Likelihood {
	if m != nil {
		return m.Adult
	}
	return Likelihood_UNKNOWN
}

func (m *SafeSearchAnnotation) GetSpoof() Likelihood {
	if m != nil {
		return m.Spoof
	}
	return Likelihood_UNKNOWN
}

func (m *SafeSearchAnnotation) GetMedical() Likelihood {
	if m != nil {
		return m.Medical
	}
	return Likelihood_UNKNOWN
}

func (m *SafeSearchAnnotation) GetViolence() Likelihood {
	if m != nil {
		return m.Violence
	}
	return Likelihood_UNKNOWN
}

func (m *SafeSearchAnnotation) GetRacy() Likelihood {
	if m != nil {
		return m.Racy
	}
	return Likelihood_UNKNOWN
}

// Rectangle determined by min and max `LatLng` pairs.
type LatLongRect struct {
	// Min lat/long pair.
	MinLatLng *google_type1.LatLng `protobuf:"bytes,1,opt,name=min_lat_lng,json=minLatLng" json:"min_lat_lng,omitempty"`
	// Max lat/long pair.
	MaxLatLng *google_type1.LatLng `protobuf:"bytes,2,opt,name=max_lat_lng,json=maxLatLng" json:"max_lat_lng,omitempty"`
}

func (m *LatLongRect) Reset()                    { *m = LatLongRect{} }
func (m *LatLongRect) String() string            { return proto.CompactTextString(m) }
func (*LatLongRect) ProtoMessage()               {}
func (*LatLongRect) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *LatLongRect) GetMinLatLng() *google_type1.LatLng {
	if m != nil {
		return m.MinLatLng
	}
	return nil
}

func (m *LatLongRect) GetMaxLatLng() *google_type1.LatLng {
	if m != nil {
		return m.MaxLatLng
	}
	return nil
}

// Color information consists of RGB channels, score, and the fraction of
// the image that the color occupies in the image.
type ColorInfo struct {
	// RGB components of the color.
	Color *google_type.Color `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
	// Image-specific score for this color. Value in range [0, 1].
	Score float32 `protobuf:"fixed32,2,opt,name=score" json:"score,omitempty"`
	// The fraction of pixels the color occupies in the image.
	// Value in range [0, 1].
	PixelFraction float32 `protobuf:"fixed32,3,opt,name=pixel_fraction,json=pixelFraction" json:"pixel_fraction,omitempty"`
}

func (m *ColorInfo) Reset()                    { *m = ColorInfo{} }
func (m *ColorInfo) String() string            { return proto.CompactTextString(m) }
func (*ColorInfo) ProtoMessage()               {}
func (*ColorInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ColorInfo) GetColor() *google_type.Color {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *ColorInfo) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ColorInfo) GetPixelFraction() float32 {
	if m != nil {
		return m.PixelFraction
	}
	return 0
}

// Set of dominant colors and their corresponding scores.
type DominantColorsAnnotation struct {
	// RGB color values with their score and pixel fraction.
	Colors []*ColorInfo `protobuf:"bytes,1,rep,name=colors" json:"colors,omitempty"`
}

func (m *DominantColorsAnnotation) Reset()                    { *m = DominantColorsAnnotation{} }
func (m *DominantColorsAnnotation) String() string            { return proto.CompactTextString(m) }
func (*DominantColorsAnnotation) ProtoMessage()               {}
func (*DominantColorsAnnotation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *DominantColorsAnnotation) GetColors() []*ColorInfo {
	if m != nil {
		return m.Colors
	}
	return nil
}

// Stores image properties, such as dominant colors.
type ImageProperties struct {
	// If present, dominant colors completed successfully.
	DominantColors *DominantColorsAnnotation `protobuf:"bytes,1,opt,name=dominant_colors,json=dominantColors" json:"dominant_colors,omitempty"`
}

func (m *ImageProperties) Reset()                    { *m = ImageProperties{} }
func (m *ImageProperties) String() string            { return proto.CompactTextString(m) }
func (*ImageProperties) ProtoMessage()               {}
func (*ImageProperties) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *ImageProperties) GetDominantColors() *DominantColorsAnnotation {
	if m != nil {
		return m.DominantColors
	}
	return nil
}

// Single crop hint that is used to generate a new crop when serving an image.
type CropHint struct {
	// The bounding polygon for the crop region. The coordinates of the bounding
	// box are in the original image's scale, as returned in `ImageParams`.
	BoundingPoly *BoundingPoly `protobuf:"bytes,1,opt,name=bounding_poly,json=boundingPoly" json:"bounding_poly,omitempty"`
	// Confidence of this being a salient region.  Range [0, 1].
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence" json:"confidence,omitempty"`
	// Fraction of importance of this salient region with respect to the original
	// image.
	ImportanceFraction float32 `protobuf:"fixed32,3,opt,name=importance_fraction,json=importanceFraction" json:"importance_fraction,omitempty"`
}

func (m *CropHint) Reset()                    { *m = CropHint{} }
func (m *CropHint) String() string            { return proto.CompactTextString(m) }
func (*CropHint) ProtoMessage()               {}
func (*CropHint) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *CropHint) GetBoundingPoly() *BoundingPoly {
	if m != nil {
		return m.BoundingPoly
	}
	return nil
}

func (m *CropHint) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *CropHint) GetImportanceFraction() float32 {
	if m != nil {
		return m.ImportanceFraction
	}
	return 0
}

// Set of crop hints that are used to generate new crops when serving images.
type CropHintsAnnotation struct {
	// Crop hint results.
	CropHints []*CropHint `protobuf:"bytes,1,rep,name=crop_hints,json=cropHints" json:"crop_hints,omitempty"`
}

func (m *CropHintsAnnotation) Reset()                    { *m = CropHintsAnnotation{} }
func (m *CropHintsAnnotation) String() string            { return proto.CompactTextString(m) }
func (*CropHintsAnnotation) ProtoMessage()               {}
func (*CropHintsAnnotation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *CropHintsAnnotation) GetCropHints() []*CropHint {
	if m != nil {
		return m.CropHints
	}
	return nil
}

// Parameters for crop hints annotation request.
type CropHintsParams struct {
	// Aspect ratios in floats, representing the ratio of the width to the height
	// of the image. For example, if the desired aspect ratio is 4/3, the
	// corresponding float value should be 1.33333.  If not specified, the
	// best possible crop is returned. The number of provided aspect ratios is
	// limited to a maximum of 16; any aspect ratios provided after the 16th are
	// ignored.
	AspectRatios []float32 `protobuf:"fixed32,1,rep,packed,name=aspect_ratios,json=aspectRatios" json:"aspect_ratios,omitempty"`
}

func (m *CropHintsParams) Reset()                    { *m = CropHintsParams{} }
func (m *CropHintsParams) String() string            { return proto.CompactTextString(m) }
func (*CropHintsParams) ProtoMessage()               {}
func (*CropHintsParams) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *CropHintsParams) GetAspectRatios() []float32 {
	if m != nil {
		return m.AspectRatios
	}
	return nil
}

// Parameters for web detection request.
type WebDetectionParams struct {
	// Whether to include results derived from the geo information in the image.
	IncludeGeoResults bool `protobuf:"varint,2,opt,name=include_geo_results,json=includeGeoResults" json:"include_geo_results,omitempty"`
}

func (m *WebDetectionParams) Reset()                    { *m = WebDetectionParams{} }
func (m *WebDetectionParams) String() string            { return proto.CompactTextString(m) }
func (*WebDetectionParams) ProtoMessage()               {}
func (*WebDetectionParams) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *WebDetectionParams) GetIncludeGeoResults() bool {
	if m != nil {
		return m.IncludeGeoResults
	}
	return false
}

// Image context and/or feature-specific parameters.
type ImageContext struct {
	// lat/long rectangle that specifies the location of the image.
	LatLongRect *LatLongRect `protobuf:"bytes,1,opt,name=lat_long_rect,json=latLongRect" json:"lat_long_rect,omitempty"`
	// List of languages to use for TEXT_DETECTION. In most cases, an empty value
	// yields the best results since it enables automatic language detection. For
	// languages based on the Latin alphabet, setting `language_hints` is not
	// needed. In rare cases, when the language of the text in the image is known,
	// setting a hint will help get better results (although it will be a
	// significant hindrance if the hint is wrong). Text detection returns an
	// error if one or more of the specified languages is not one of the
	// [supported languages](/vision/docs/languages).
	LanguageHints []string `protobuf:"bytes,2,rep,name=language_hints,json=languageHints" json:"language_hints,omitempty"`
	// Parameters for crop hints annotation request.
	CropHintsParams *CropHintsParams `protobuf:"bytes,4,opt,name=crop_hints_params,json=cropHintsParams" json:"crop_hints_params,omitempty"`
	// Parameters for web detection.
	WebDetectionParams *WebDetectionParams `protobuf:"bytes,6,opt,name=web_detection_params,json=webDetectionParams" json:"web_detection_params,omitempty"`
}

func (m *ImageContext) Reset()                    { *m = ImageContext{} }
func (m *ImageContext) String() string            { return proto.CompactTextString(m) }
func (*ImageContext) ProtoMessage()               {}
func (*ImageContext) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *ImageContext) GetLatLongRect() *LatLongRect {
	if m != nil {
		return m.LatLongRect
	}
	return nil
}

func (m *ImageContext) GetLanguageHints() []string {
	if m != nil {
		return m.LanguageHints
	}
	return nil
}

func (m *ImageContext) GetCropHintsParams() *CropHintsParams {
	if m != nil {
		return m.CropHintsParams
	}
	return nil
}

func (m *ImageContext) GetWebDetectionParams() *WebDetectionParams {
	if m != nil {
		return m.WebDetectionParams
	}
	return nil
}

// Request for performing Google Cloud Vision API tasks over a user-provided
// image, with user-requested features.
type AnnotateImageRequest struct {
	// The image to be processed.
	Image *Image `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	// Requested features.
	Features []*Feature `protobuf:"bytes,2,rep,name=features" json:"features,omitempty"`
	// Additional context that may accompany the image.
	ImageContext *ImageContext `protobuf:"bytes,3,opt,name=image_context,json=imageContext" json:"image_context,omitempty"`
}

func (m *AnnotateImageRequest) Reset()                    { *m = AnnotateImageRequest{} }
func (m *AnnotateImageRequest) String() string            { return proto.CompactTextString(m) }
func (*AnnotateImageRequest) ProtoMessage()               {}
func (*AnnotateImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *AnnotateImageRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *AnnotateImageRequest) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *AnnotateImageRequest) GetImageContext() *ImageContext {
	if m != nil {
		return m.ImageContext
	}
	return nil
}

// Response to an image annotation request.
type AnnotateImageResponse struct {
	// If present, face detection has completed successfully.
	FaceAnnotations []*FaceAnnotation `protobuf:"bytes,1,rep,name=face_annotations,json=faceAnnotations" json:"face_annotations,omitempty"`
	// If present, landmark detection has completed successfully.
	LandmarkAnnotations []*EntityAnnotation `protobuf:"bytes,2,rep,name=landmark_annotations,json=landmarkAnnotations" json:"landmark_annotations,omitempty"`
	// If present, logo detection has completed successfully.
	LogoAnnotations []*EntityAnnotation `protobuf:"bytes,3,rep,name=logo_annotations,json=logoAnnotations" json:"logo_annotations,omitempty"`
	// If present, label detection has completed successfully.
	LabelAnnotations []*EntityAnnotation `protobuf:"bytes,4,rep,name=label_annotations,json=labelAnnotations" json:"label_annotations,omitempty"`
	// If present, text (OCR) detection has completed successfully.
	TextAnnotations []*EntityAnnotation `protobuf:"bytes,5,rep,name=text_annotations,json=textAnnotations" json:"text_annotations,omitempty"`
	// If present, text (OCR) detection or document (OCR) text detection has
	// completed successfully.
	// This annotation provides the structural hierarchy for the OCR detected
	// text.
	FullTextAnnotation *TextAnnotation `protobuf:"bytes,12,opt,name=full_text_annotation,json=fullTextAnnotation" json:"full_text_annotation,omitempty"`
	// If present, safe-search annotation has completed successfully.
	SafeSearchAnnotation *SafeSearchAnnotation `protobuf:"bytes,6,opt,name=safe_search_annotation,json=safeSearchAnnotation" json:"safe_search_annotation,omitempty"`
	// If present, image properties were extracted successfully.
	ImagePropertiesAnnotation *ImageProperties `protobuf:"bytes,8,opt,name=image_properties_annotation,json=imagePropertiesAnnotation" json:"image_properties_annotation,omitempty"`
	// If present, crop hints have completed successfully.
	CropHintsAnnotation *CropHintsAnnotation `protobuf:"bytes,11,opt,name=crop_hints_annotation,json=cropHintsAnnotation" json:"crop_hints_annotation,omitempty"`
	// If present, web detection has completed successfully.
	WebDetection *WebDetection `protobuf:"bytes,13,opt,name=web_detection,json=webDetection" json:"web_detection,omitempty"`
	// If set, represents the error message for the operation.
	// Note that filled-in image annotations are guaranteed to be
	// correct, even when `error` is set.
	Error *google_rpc.Status `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *AnnotateImageResponse) Reset()                    { *m = AnnotateImageResponse{} }
func (m *AnnotateImageResponse) String() string            { return proto.CompactTextString(m) }
func (*AnnotateImageResponse) ProtoMessage()               {}
func (*AnnotateImageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *AnnotateImageResponse) GetFaceAnnotations() []*FaceAnnotation {
	if m != nil {
		return m.FaceAnnotations
	}
	return nil
}

func (m *AnnotateImageResponse) GetLandmarkAnnotations() []*EntityAnnotation {
	if m != nil {
		return m.LandmarkAnnotations
	}
	return nil
}

func (m *AnnotateImageResponse) GetLogoAnnotations() []*EntityAnnotation {
	if m != nil {
		return m.LogoAnnotations
	}
	return nil
}

func (m *AnnotateImageResponse) GetLabelAnnotations() []*EntityAnnotation {
	if m != nil {
		return m.LabelAnnotations
	}
	return nil
}

func (m *AnnotateImageResponse) GetTextAnnotations() []*EntityAnnotation {
	if m != nil {
		return m.TextAnnotations
	}
	return nil
}

func (m *AnnotateImageResponse) GetFullTextAnnotation() *TextAnnotation {
	if m != nil {
		return m.FullTextAnnotation
	}
	return nil
}

func (m *AnnotateImageResponse) GetSafeSearchAnnotation() *SafeSearchAnnotation {
	if m != nil {
		return m.SafeSearchAnnotation
	}
	return nil
}

func (m *AnnotateImageResponse) GetImagePropertiesAnnotation() *ImageProperties {
	if m != nil {
		return m.ImagePropertiesAnnotation
	}
	return nil
}

func (m *AnnotateImageResponse) GetCropHintsAnnotation() *CropHintsAnnotation {
	if m != nil {
		return m.CropHintsAnnotation
	}
	return nil
}

func (m *AnnotateImageResponse) GetWebDetection() *WebDetection {
	if m != nil {
		return m.WebDetection
	}
	return nil
}

func (m *AnnotateImageResponse) GetError() *google_rpc.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

// Multiple image annotation requests are batched into a single service call.
type BatchAnnotateImagesRequest struct {
	// Individual image annotation requests for this batch.
	Requests []*AnnotateImageRequest `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
}

func (m *BatchAnnotateImagesRequest) Reset()                    { *m = BatchAnnotateImagesRequest{} }
func (m *BatchAnnotateImagesRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchAnnotateImagesRequest) ProtoMessage()               {}
func (*BatchAnnotateImagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *BatchAnnotateImagesRequest) GetRequests() []*AnnotateImageRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

// Response to a batch image annotation request.
type BatchAnnotateImagesResponse struct {
	// Individual responses to image annotation requests within the batch.
	Responses []*AnnotateImageResponse `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
}

func (m *BatchAnnotateImagesResponse) Reset()                    { *m = BatchAnnotateImagesResponse{} }
func (m *BatchAnnotateImagesResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchAnnotateImagesResponse) ProtoMessage()               {}
func (*BatchAnnotateImagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *BatchAnnotateImagesResponse) GetResponses() []*AnnotateImageResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

func init() {
	proto.RegisterType((*Feature)(nil), "google.cloud.vision.v1p1beta1.Feature")
	proto.RegisterType((*ImageSource)(nil), "google.cloud.vision.v1p1beta1.ImageSource")
	proto.RegisterType((*Image)(nil), "google.cloud.vision.v1p1beta1.Image")
	proto.RegisterType((*FaceAnnotation)(nil), "google.cloud.vision.v1p1beta1.FaceAnnotation")
	proto.RegisterType((*FaceAnnotation_Landmark)(nil), "google.cloud.vision.v1p1beta1.FaceAnnotation.Landmark")
	proto.RegisterType((*LocationInfo)(nil), "google.cloud.vision.v1p1beta1.LocationInfo")
	proto.RegisterType((*Property)(nil), "google.cloud.vision.v1p1beta1.Property")
	proto.RegisterType((*EntityAnnotation)(nil), "google.cloud.vision.v1p1beta1.EntityAnnotation")
	proto.RegisterType((*SafeSearchAnnotation)(nil), "google.cloud.vision.v1p1beta1.SafeSearchAnnotation")
	proto.RegisterType((*LatLongRect)(nil), "google.cloud.vision.v1p1beta1.LatLongRect")
	proto.RegisterType((*ColorInfo)(nil), "google.cloud.vision.v1p1beta1.ColorInfo")
	proto.RegisterType((*DominantColorsAnnotation)(nil), "google.cloud.vision.v1p1beta1.DominantColorsAnnotation")
	proto.RegisterType((*ImageProperties)(nil), "google.cloud.vision.v1p1beta1.ImageProperties")
	proto.RegisterType((*CropHint)(nil), "google.cloud.vision.v1p1beta1.CropHint")
	proto.RegisterType((*CropHintsAnnotation)(nil), "google.cloud.vision.v1p1beta1.CropHintsAnnotation")
	proto.RegisterType((*CropHintsParams)(nil), "google.cloud.vision.v1p1beta1.CropHintsParams")
	proto.RegisterType((*WebDetectionParams)(nil), "google.cloud.vision.v1p1beta1.WebDetectionParams")
	proto.RegisterType((*ImageContext)(nil), "google.cloud.vision.v1p1beta1.ImageContext")
	proto.RegisterType((*AnnotateImageRequest)(nil), "google.cloud.vision.v1p1beta1.AnnotateImageRequest")
	proto.RegisterType((*AnnotateImageResponse)(nil), "google.cloud.vision.v1p1beta1.AnnotateImageResponse")
	proto.RegisterType((*BatchAnnotateImagesRequest)(nil), "google.cloud.vision.v1p1beta1.BatchAnnotateImagesRequest")
	proto.RegisterType((*BatchAnnotateImagesResponse)(nil), "google.cloud.vision.v1p1beta1.BatchAnnotateImagesResponse")
	proto.RegisterEnum("google.cloud.vision.v1p1beta1.Likelihood", Likelihood_name, Likelihood_value)
	proto.RegisterEnum("google.cloud.vision.v1p1beta1.Feature_Type", Feature_Type_name, Feature_Type_value)
	proto.RegisterEnum("google.cloud.vision.v1p1beta1.FaceAnnotation_Landmark_Type", FaceAnnotation_Landmark_Type_name, FaceAnnotation_Landmark_Type_value)
}

func init() {
	proto.RegisterFile("google/cloud/vision/v1p1beta1/image_annotator.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 2362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0x4f, 0x73, 0xdb, 0xc6,
	0x15, 0x0f, 0xa9, 0x7f, 0xe4, 0xe3, 0x3f, 0x68, 0x25, 0x2b, 0xb4, 0x6c, 0xc7, 0x0a, 0xda, 0xb4,
	0x6a, 0x9a, 0x52, 0x63, 0x39, 0x4d, 0xa7, 0x6e, 0x33, 0x29, 0x49, 0x41, 0x12, 0x27, 0x34, 0x89,
	0x59, 0x52, 0x51, 0x9c, 0x49, 0x07, 0x85, 0xc0, 0x25, 0x8d, 0x04, 0xc4, 0x22, 0x00, 0x68, 0x4b,
	0xd7, 0x5e, 0x7b, 0xec, 0xad, 0xf7, 0x1e, 0x7b, 0x6a, 0x3f, 0x43, 0xbe, 0x40, 0x0f, 0xfd, 0x00,
	0xed, 0xa1, 0x9f, 0xa0, 0xd3, 0xe9, 0xa9, 0xb3, 0x7f, 0x00, 0x2e, 0x68, 0xc7, 0x34, 0xdd, 0xe9,
	0x89, 0xd8, 0xf7, 0xf6, 0xf7, 0x7b, 0xbb, 0xef, 0xed, 0xdb, 0x7d, 0xbb, 0x84, 0x87, 0x13, 0x4a,
	0x27, 0x1e, 0x39, 0x72, 0x3c, 0x3a, 0x1b, 0x1d, 0x3d, 0x73, 0x23, 0x97, 0xfa, 0x47, 0xcf, 0x1e,
	0x04, 0x0f, 0xae, 0x48, 0x6c, 0x3f, 0x38, 0x72, 0xa7, 0xf6, 0x84, 0x58, 0xb6, 0xef, 0xd3, 0xd8,
	0x8e, 0x69, 0xd8, 0x08, 0x42, 0x1a, 0x53, 0x74, 0x4f, 0x80, 0x1a, 0x1c, 0xd4, 0x10, 0xa0, 0x46,
	0x0a, 0xda, 0xbf, 0x2b, 0x39, 0xed, 0xc0, 0x3d, 0x92, 0x50, 0x97, 0xfa, 0x91, 0x00, 0xef, 0x7f,
	0xf0, 0x6a, 0x8b, 0x13, 0x42, 0xa7, 0x24, 0x0e, 0x6f, 0x64, 0xef, 0x25, 0xe3, 0x8b, 0xc9, 0x75,
	0x6c, 0xcd, 0x6d, 0x48, 0xd0, 0x83, 0x57, 0x83, 0x9e, 0x93, 0x2b, 0x6b, 0x44, 0x62, 0xe2, 0x28,
	0x90, 0xb7, 0x25, 0x24, 0x0c, 0x9c, 0xa3, 0x28, 0xb6, 0xe3, 0x59, 0xb4, 0xa0, 0x88, 0x6f, 0x02,
	0x72, 0xe4, 0x50, 0x2f, 0x71, 0xc2, 0x7e, 0x5d, 0x55, 0x78, 0x76, 0xec, 0xf9, 0x13, 0xa1, 0xd1,
	0xff, 0x93, 0x87, 0xad, 0x53, 0x62, 0xc7, 0xb3, 0x90, 0xa0, 0x4f, 0x60, 0x9d, 0x75, 0xa8, 0xe7,
	0x0e, 0x72, 0x87, 0xd5, 0xe3, 0x1f, 0x37, 0x5e, 0xe9, 0xb9, 0x86, 0x44, 0x35, 0x86, 0x37, 0x01,
	0xc1, 0x1c, 0x88, 0xee, 0x43, 0x69, 0x6a, 0x5f, 0x5b, 0x21, 0x89, 0x66, 0x5e, 0x1c, 0xd5, 0xf3,
	0x07, 0xb9, 0xc3, 0x0d, 0x0c, 0x53, 0xfb, 0x1a, 0x0b, 0x09, 0xda, 0x85, 0x8d, 0x29, 0x1d, 0x11,
	0xaf, 0xbe, 0x76, 0x90, 0x3b, 0x2c, 0x62, 0xd1, 0xd0, 0xff, 0x95, 0x83, 0x75, 0xc6, 0x82, 0x76,
	0x41, 0x1b, 0x3e, 0x31, 0x0d, 0xeb, 0xa2, 0x37, 0x30, 0x8d, 0x76, 0xe7, 0xb4, 0x63, 0x9c, 0x68,
	0x6f, 0x21, 0x04, 0xd5, 0xd3, 0x66, 0xdb, 0xb0, 0x4e, 0x8c, 0xa1, 0xd1, 0x1e, 0x76, 0xfa, 0x3d,
	0x2d, 0x87, 0xf6, 0x00, 0x75, 0x9b, 0xbd, 0x93, 0xc7, 0x4d, 0xfc, 0xa9, 0x22, 0xcf, 0xb3, 0xbe,
	0xdd, 0xfe, 0x59, 0x5f, 0x91, 0xad, 0xa1, 0x1d, 0xa8, 0x75, 0x9b, 0x2d, 0xa3, 0xab, 0x08, 0xd7,
	0x59, 0xc7, 0xa1, 0xf1, 0xf9, 0x50, 0x91, 0x6d, 0xa0, 0x3b, 0xf0, 0xf6, 0x49, 0xbf, 0x7d, 0xf1,
	0xd8, 0xe8, 0x0d, 0xad, 0x05, 0x65, 0x09, 0xdd, 0x86, 0x5b, 0x83, 0xe6, 0xa9, 0x61, 0x0d, 0x8c,
	0x26, 0x6e, 0x9f, 0x2b, 0xaa, 0x4d, 0x36, 0xec, 0xce, 0xe3, 0xe6, 0x99, 0x61, 0x99, 0xb8, 0x6f,
	0x1a, 0x78, 0xd8, 0x31, 0x06, 0xda, 0x16, 0xaa, 0x02, 0xb4, 0x71, 0xdf, 0xb4, 0xce, 0x3b, 0xbd,
	0xe1, 0x40, 0x2b, 0xa2, 0x6d, 0xa8, 0x5c, 0x1a, 0x2d, 0x05, 0x08, 0x7a, 0x0f, 0x4a, 0x1d, 0xb6,
	0x68, 0x07, 0x74, 0x16, 0x3a, 0x04, 0xe9, 0x50, 0x99, 0x38, 0x91, 0x25, 0xd6, 0xf1, 0x2c, 0x74,
	0x79, 0x20, 0x8a, 0xb8, 0x34, 0x71, 0x22, 0xde, 0xed, 0x22, 0x74, 0xd1, 0x1d, 0x28, 0xce, 0xf5,
	0x79, 0xae, 0x2f, 0xb8, 0x52, 0xa9, 0x13, 0xd8, 0xe0, 0x1d, 0x51, 0x1d, 0xb6, 0x1c, 0xea, 0xc7,
	0xc4, 0x8f, 0x39, 0x47, 0x19, 0x27, 0x4d, 0xd4, 0x82, 0xcd, 0x88, 0x5b, 0xe3, 0xe0, 0xd2, 0xf1,
	0xfb, 0x4b, 0xa2, 0xac, 0x8c, 0x0f, 0x4b, 0xa4, 0xfe, 0x47, 0x0d, 0xaa, 0xa7, 0xb6, 0x43, 0x9a,
	0xe9, 0x5a, 0x46, 0x26, 0x54, 0xae, 0xe8, 0xcc, 0x1f, 0xb9, 0xfe, 0xc4, 0x0a, 0xa8, 0x77, 0xc3,
	0xcd, 0x96, 0x96, 0xae, 0xa1, 0x96, 0xc4, 0x98, 0xd4, 0xbb, 0xc1, 0xe5, 0x2b, 0xa5, 0x85, 0x2e,
	0x40, 0x1b, 0x8f, 0xac, 0x2c, 0x69, 0x7e, 0x75, 0xd2, 0xea, 0x78, 0xa4, 0xb6, 0xd1, 0x10, 0x8a,
	0x9e, 0xed, 0x8f, 0xa6, 0x76, 0xf8, 0x75, 0x54, 0x5f, 0x3b, 0x58, 0x3b, 0x2c, 0x1d, 0x7f, 0xb4,
	0x6c, 0xa1, 0x67, 0xa6, 0xda, 0xe8, 0x4a, 0x38, 0x9e, 0x13, 0xa1, 0x7b, 0x00, 0x21, 0xf5, 0x3c,
	0xcb, 0xf6, 0x27, 0x1e, 0xa9, 0xaf, 0x1f, 0xe4, 0x0e, 0xf3, 0xb8, 0xc8, 0x24, 0x4d, 0x26, 0x60,
	0x41, 0x0b, 0x6c, 0x5f, 0x6a, 0x37, 0xb8, 0xb6, 0x10, 0xd8, 0xbe, 0x50, 0xde, 0x03, 0x88, 0x5d,
	0x2f, 0x96, 0xda, 0x4d, 0x81, 0x65, 0x12, 0xa1, 0x7e, 0x00, 0xbb, 0x69, 0xfe, 0x5b, 0x0e, 0xf5,
	0xc7, 0xee, 0x88, 0xf8, 0x0e, 0xa9, 0x6f, 0xf1, 0x8e, 0x3b, 0xa9, 0xae, 0x9d, 0xaa, 0xd0, 0x4f,
	0x61, 0x2f, 0x19, 0x1a, 0x73, 0x9d, 0x02, 0x2a, 0x70, 0xd0, 0x2d, 0x45, 0xab, 0xc0, 0x4c, 0xa8,
	0x7e, 0x45, 0x6f, 0x2c, 0xcf, 0xfd, 0x9a, 0x78, 0xee, 0x53, 0x4a, 0x47, 0xf5, 0x22, 0xdf, 0x08,
	0x7e, 0xb4, 0xc4, 0x3f, 0xdd, 0x14, 0x80, 0x2b, 0x5f, 0xd1, 0x9b, 0x79, 0x13, 0x7d, 0x06, 0xdb,
	0x11, 0x0d, 0x43, 0xfa, 0x5c, 0x25, 0x85, 0x55, 0x49, 0x35, 0xc1, 0xa1, 0xf0, 0x0e, 0x41, 0xb3,
	0xfd, 0x09, 0x09, 0x55, 0xda, 0xd2, 0xaa, 0xb4, 0x35, 0x4e, 0xa1, 0xb0, 0x7e, 0x01, 0x3b, 0xd1,
	0x2c, 0x0c, 0x42, 0x37, 0x22, 0x2a, 0x71, 0x79, 0x55, 0x62, 0x94, 0xb0, 0x28, 0xdc, 0x0e, 0xd4,
	0x67, 0xfe, 0x88, 0x84, 0x16, 0xb9, 0x0e, 0x68, 0x44, 0x46, 0xaa, 0x81, 0xca, 0xaa, 0x06, 0xf6,
	0x38, 0x95, 0x21, 0x98, 0x14, 0x23, 0x9f, 0x03, 0xba, 0xf2, 0x66, 0x61, 0x98, 0xa5, 0xaf, 0xae,
	0x4a, 0xbf, 0x2d, 0x49, 0xb2, 0xae, 0x79, 0x4a, 0xec, 0xd1, 0x73, 0x62, 0x67, 0x7c, 0x5e, 0x5b,
	0xd9, 0x35, 0x09, 0xcb, 0x5c, 0xb6, 0xff, 0xb7, 0x2d, 0x28, 0x24, 0x39, 0x85, 0xfa, 0xf2, 0x08,
	0x5a, 0xe3, 0xcc, 0xbf, 0x78, 0xb3, 0xcc, 0x54, 0x8f, 0xa4, 0x36, 0x14, 0x02, 0x1a, 0xb9, 0x4c,
	0xcf, 0xf3, 0xb2, 0x74, 0xfc, 0xc3, 0x25, 0xa4, 0xa6, 0xec, 0x8e, 0x53, 0xa0, 0xfe, 0x97, 0xcd,
	0xf9, 0x01, 0x75, 0xd1, 0xfb, 0xb4, 0xd7, 0xbf, 0xec, 0x59, 0xc9, 0xf1, 0xa3, 0xbd, 0x85, 0xca,
	0x50, 0xe8, 0x1a, 0xa7, 0x43, 0xcb, 0x78, 0x62, 0x68, 0x39, 0x54, 0x81, 0x22, 0xee, 0x9c, 0x9d,
	0x8b, 0x66, 0x1e, 0xd5, 0x61, 0x97, 0x2b, 0xfb, 0xa7, 0x56, 0xd2, 0xa9, 0x85, 0xfb, 0x97, 0xda,
	0x1a, 0x3b, 0x51, 0x44, 0xc7, 0x45, 0xd5, 0x3a, 0x53, 0x25, 0xa0, 0x94, 0x8b, 0xab, 0x36, 0xd0,
	0x3e, 0xec, 0xa5, 0xa8, 0xac, 0x6e, 0x93, 0xc1, 0x1e, 0x77, 0x4e, 0xcc, 0x7e, 0xa7, 0x37, 0xb4,
	0x5a, 0xc6, 0xf0, 0xd2, 0x30, 0x7a, 0x4c, 0xcb, 0x4e, 0xa3, 0x32, 0x14, 0x7a, 0xfd, 0x81, 0x61,
	0x0d, 0x3b, 0xa6, 0x56, 0x60, 0x63, 0xbc, 0x30, 0x4d, 0x03, 0x5b, 0xdd, 0x8e, 0xa9, 0x15, 0x59,
	0xb3, 0xdb, 0xbf, 0x94, 0x4d, 0x60, 0x27, 0xd7, 0xe3, 0xfe, 0xc5, 0xf0, 0x9c, 0x8f, 0x4a, 0x2b,
	0xa1, 0x1a, 0x94, 0x44, 0x9b, 0xdb, 0xd3, 0xca, 0x48, 0x83, 0xb2, 0x10, 0xb4, 0x8d, 0xde, 0xd0,
	0xc0, 0x5a, 0x05, 0xdd, 0x82, 0x6d, 0x4e, 0xdf, 0xea, 0x0f, 0x87, 0xfd, 0xc7, 0xb2, 0x63, 0x95,
	0xf9, 0x4b, 0x15, 0x73, 0xbe, 0x1a, 0x3b, 0xbc, 0x55, 0xa9, 0x24, 0xd1, 0xd2, 0x59, 0x1b, 0x4f,
	0x0c, 0x6b, 0xd8, 0x37, 0xad, 0x56, 0xff, 0xa2, 0x77, 0xd2, 0xc4, 0x4f, 0xb4, 0xed, 0x8c, 0x4a,
	0xcc, 0xba, 0xdd, 0xc7, 0x3d, 0x03, 0x6b, 0x08, 0xdd, 0x85, 0x7a, 0xaa, 0x92, 0x8c, 0x29, 0x70,
	0x27, 0x75, 0x3f, 0xd3, 0xf2, 0x0f, 0x89, 0xdb, 0x9d, 0x3b, 0xf2, 0x05, 0x73, 0xb7, 0xb2, 0xba,
	0x8c, 0xbd, 0x3d, 0x74, 0x0f, 0x6e, 0xcf, 0x75, 0x8b, 0x06, 0xdf, 0x9e, 0x47, 0x75, 0xd1, 0x62,
	0x1d, 0xdd, 0x87, 0x3b, 0x6a, 0x9c, 0x2d, 0x11, 0x82, 0x24, 0x62, 0xda, 0x6d, 0x74, 0x00, 0x77,
	0x33, 0x21, 0x5d, 0xec, 0xb1, 0xcf, 0x1c, 0x2a, 0x28, 0x9a, 0xd8, 0x1a, 0xe2, 0xe6, 0x19, 0xab,
	0x23, 0xee, 0x30, 0xef, 0x4b, 0x9c, 0x22, 0xbe, 0xcb, 0x8b, 0xa1, 0x64, 0xee, 0xe6, 0x85, 0xd9,
	0xe9, 0x6a, 0xf7, 0x58, 0x31, 0x34, 0x1f, 0x9e, 0x10, 0xbe, 0xc3, 0xf0, 0xa7, 0x7d, 0x6c, 0x9c,
	0x1b, 0xcd, 0x13, 0xeb, 0x8c, 0xd7, 0x4a, 0xdd, 0xa6, 0x76, 0x9f, 0x55, 0x2c, 0xed, 0xf3, 0x4e,
	0xcf, 0x3a, 0xeb, 0x35, 0x87, 0xe7, 0x8c, 0xf2, 0x80, 0xd9, 0xe7, 0x22, 0xce, 0x7b, 0xd6, 0xef,
	0x31, 0xe9, 0xbb, 0x0c, 0xcf, 0xa5, 0x82, 0x59, 0x8a, 0x75, 0xfd, 0x97, 0x50, 0xee, 0x52, 0x87,
	0xe7, 0x66, 0xc7, 0x1f, 0x53, 0xf4, 0x01, 0x6c, 0x79, 0x76, 0x6c, 0x79, 0xfe, 0x44, 0x96, 0x07,
	0x3b, 0x49, 0x2a, 0xb2, 0x54, 0x6d, 0x74, 0xed, 0xb8, 0xeb, 0x4f, 0xf0, 0xa6, 0xc7, 0x7f, 0xf5,
	0x4b, 0x28, 0x98, 0x21, 0x0d, 0x48, 0x18, 0xdf, 0x20, 0x04, 0xeb, 0xbe, 0x3d, 0x25, 0xb2, 0x20,
	0xe2, 0xdf, 0xac, 0x96, 0x7c, 0x66, 0x7b, 0x33, 0x22, 0xab, 0x20, 0xd1, 0x40, 0xef, 0x42, 0x79,
	0xe6, 0xfa, 0xf1, 0x47, 0x1f, 0x5a, 0x42, 0xc9, 0x36, 0x92, 0x75, 0x5c, 0x12, 0xb2, 0xcf, 0x98,
	0x48, 0xff, 0xc3, 0x1a, 0x68, 0x86, 0x1f, 0xbb, 0xf1, 0x8d, 0x52, 0xc0, 0x68, 0xb0, 0x36, 0x75,
	0x47, 0xd2, 0x00, 0xfb, 0x44, 0x7b, 0xb0, 0xe9, 0x51, 0xc7, 0xf6, 0x12, 0x03, 0xb2, 0x85, 0x0e,
	0xa0, 0x34, 0x22, 0x91, 0x13, 0xba, 0x01, 0xdf, 0x54, 0x44, 0x25, 0xab, 0x8a, 0xd8, 0xc8, 0x22,
	0x87, 0x86, 0x49, 0x21, 0x20, 0x1a, 0xe8, 0x1d, 0x00, 0xe5, 0x24, 0x16, 0x55, 0x80, 0x22, 0x61,
	0xfa, 0x98, 0x06, 0xae, 0x63, 0x7b, 0x6e, 0x7c, 0x23, 0xeb, 0x00, 0x45, 0xf2, 0x62, 0x89, 0xb5,
	0xf5, 0xbf, 0x96, 0x58, 0x1d, 0x28, 0x7a, 0x32, 0x3e, 0x51, 0xbd, 0xc0, 0x6b, 0xa1, 0x65, 0x6c,
	0x6a, 0x3c, 0xf1, 0x1c, 0x8d, 0xce, 0x00, 0x02, 0x11, 0x2c, 0x97, 0x44, 0xf5, 0x22, 0xe7, 0x5a,
	0xba, 0xd1, 0xca, 0xe8, 0x62, 0x05, 0xaa, 0xff, 0x3d, 0x0f, 0xbb, 0x03, 0x7b, 0x4c, 0x06, 0xc4,
	0x0e, 0x9d, 0xa7, 0x4a, 0x80, 0x3e, 0x81, 0x0d, 0x7b, 0x34, 0xf3, 0x62, 0x79, 0x3b, 0x59, 0xe1,
	0xd0, 0x11, 0x38, 0x46, 0x10, 0x05, 0x94, 0x8e, 0x79, 0x38, 0x57, 0x23, 0xe0, 0x38, 0xd4, 0x86,
	0xad, 0x29, 0x19, 0xb1, 0x70, 0xc8, 0xe3, 0x69, 0x05, 0x8a, 0x04, 0x89, 0x0c, 0x28, 0x3c, 0x73,
	0xa9, 0xc7, 0xd7, 0xc0, 0xfa, 0xaa, 0x2c, 0x29, 0x14, 0x7d, 0x0c, 0xeb, 0xa1, 0xed, 0xdc, 0xac,
	0x5e, 0xa1, 0x71, 0x98, 0xfe, 0x1c, 0x4a, 0x2c, 0xdb, 0xa8, 0x3f, 0xc1, 0xc4, 0x89, 0xd1, 0x43,
	0x28, 0x4d, 0x5d, 0xdf, 0x7a, 0x8d, 0xe4, 0x2c, 0x4e, 0x5d, 0x5f, 0x7c, 0x72, 0x90, 0x7d, 0x9d,
	0x82, 0xf2, 0xaf, 0x02, 0xd9, 0xd7, 0xe2, 0x53, 0x0f, 0xa1, 0xd8, 0x66, 0xf7, 0x52, 0xbe, 0x1f,
	0x1c, 0xc2, 0x06, 0xbf, 0xa4, 0x4a, 0x83, 0x28, 0x83, 0xe5, 0xdd, 0xb0, 0xe8, 0x30, 0xcf, 0xa8,
	0xbc, 0x9a, 0x51, 0xef, 0x41, 0x35, 0x70, 0xaf, 0x89, 0x67, 0x8d, 0x43, 0xdb, 0x49, 0x93, 0x31,
	0x8f, 0x2b, 0x5c, 0x7a, 0x2a, 0x85, 0xfa, 0x97, 0x50, 0x3f, 0xa1, 0x53, 0xd7, 0xb7, 0xfd, 0x98,
	0x93, 0x46, 0xca, 0xaa, 0xfa, 0x15, 0x6c, 0x72, 0x0b, 0x51, 0x3d, 0xc7, 0xd7, 0xec, 0xe1, 0x12,
	0x4f, 0xa6, 0x83, 0xc7, 0x12, 0xa7, 0x47, 0x50, 0xe3, 0x77, 0x24, 0x33, 0x5d, 0xc3, 0xe8, 0x37,
	0x50, 0x1b, 0x49, 0x83, 0x56, 0xca, 0xce, 0x66, 0xf8, 0xb3, 0x25, 0xec, 0xdf, 0x35, 0x4c, 0x5c,
	0x1d, 0x65, 0x34, 0xfa, 0x9f, 0x72, 0x50, 0x68, 0x87, 0x34, 0x38, 0x77, 0xfd, 0xf8, 0xff, 0x70,
	0xf7, 0xca, 0x6e, 0x55, 0xf9, 0x17, 0xb6, 0xaa, 0x23, 0xd8, 0x71, 0xa7, 0x01, 0x0d, 0x63, 0xdb,
	0x77, 0xc8, 0xa2, 0xf7, 0xd1, 0x5c, 0x95, 0x86, 0xe0, 0xd7, 0xb0, 0x93, 0x0c, 0x57, 0xf5, 0xfe,
	0x29, 0x80, 0x13, 0xd2, 0xc0, 0x7a, 0xca, 0xe4, 0x32, 0x02, 0xcb, 0x76, 0x8d, 0x84, 0x07, 0x17,
	0x9d, 0x84, 0x51, 0xff, 0x08, 0x6a, 0x29, 0xbd, 0x69, 0x87, 0xf6, 0x34, 0x42, 0xdf, 0x83, 0x8a,
	0x1d, 0x05, 0xc4, 0x89, 0xad, 0x90, 0xd9, 0x12, 0xec, 0x79, 0x5c, 0x16, 0x42, 0xcc, 0x65, 0xfa,
	0x09, 0xa0, 0x4b, 0x72, 0x75, 0x92, 0x5c, 0xa1, 0x24, 0xb4, 0x01, 0x3b, 0xae, 0xef, 0x78, 0xb3,
	0x11, 0xb1, 0x26, 0x84, 0x66, 0x5e, 0x33, 0x0a, 0x78, 0x5b, 0xaa, 0xce, 0x08, 0x95, 0x8f, 0x1a,
	0xfa, 0xb7, 0x79, 0x28, 0xf3, 0x25, 0xd0, 0x66, 0x77, 0xec, 0xeb, 0x18, 0xf5, 0xa0, 0xc2, 0xb3,
	0x82, 0xfa, 0x13, 0x2b, 0x24, 0x4e, 0x2c, 0x03, 0xb2, 0xec, 0xaa, 0xad, 0x64, 0x24, 0x2e, 0x79,
	0x4a, 0x7a, 0xbe, 0x07, 0x55, 0xcf, 0xf6, 0x27, 0x33, 0x76, 0xed, 0x17, 0xae, 0xca, 0x1f, 0xac,
	0x1d, 0x16, 0x71, 0x25, 0x91, 0xf2, 0x89, 0xa3, 0x2f, 0x60, 0x7b, 0xee, 0x4d, 0x2b, 0xe0, 0x93,
	0x91, 0x35, 0x6f, 0xe3, 0x35, 0x9d, 0x2a, 0xbd, 0x87, 0x6b, 0xce, 0x82, 0x3b, 0x1d, 0xd8, 0xcd,
	0xbc, 0x44, 0x25, 0xf4, 0x9b, 0x9c, 0xfe, 0xc1, 0x12, 0xfa, 0x17, 0x9d, 0x8c, 0xd1, 0xf3, 0x17,
	0x64, 0xfa, 0x3f, 0x73, 0xb0, 0x2b, 0x57, 0x07, 0xe1, 0x0e, 0xc5, 0xe4, 0x9b, 0x19, 0x89, 0x62,
	0xf4, 0x08, 0x36, 0xf8, 0x1b, 0x87, 0x74, 0xe4, 0xf7, 0x5f, 0xe7, 0xcd, 0x02, 0x0b, 0x08, 0x6a,
	0x41, 0x61, 0x2c, 0x5e, 0xaa, 0x84, 0xdb, 0x4a, 0xc7, 0x3f, 0x78, 0xbd, 0x87, 0x2d, 0x9c, 0xe2,
	0x58, 0x86, 0x89, 0x47, 0x17, 0x47, 0x44, 0x98, 0xaf, 0xf4, 0xe5, 0x19, 0xa6, 0x2e, 0x0a, 0x5c,
	0x76, 0x95, 0x96, 0xfe, 0xbb, 0x02, 0xdc, 0x5a, 0x98, 0x6a, 0x14, 0x50, 0x3f, 0x22, 0xe8, 0x73,
	0xd0, 0xc6, 0xb6, 0x43, 0x94, 0x87, 0xc2, 0x24, 0x33, 0x7e, 0xb2, 0xd2, 0x6d, 0x08, 0xd7, 0xc6,
	0x99, 0x76, 0x84, 0xae, 0x60, 0x37, 0xb9, 0xf8, 0x67, 0xd8, 0x85, 0x57, 0x8e, 0x96, 0xb0, 0x2f,
	0x56, 0x4c, 0x78, 0x27, 0x21, 0x53, 0x6d, 0x7c, 0x01, 0x9a, 0x47, 0x27, 0x34, 0xc3, 0xbf, 0xf6,
	0x66, 0xfc, 0x35, 0x46, 0xa4, 0x72, 0x7f, 0x09, 0xdb, 0x9e, 0x7d, 0x45, 0xbc, 0x0c, 0xf9, 0xfa,
	0x9b, 0x91, 0x6b, 0x9c, 0x69, 0x61, 0xe4, 0x0b, 0x0f, 0xb4, 0x51, 0x7d, 0xe3, 0x0d, 0x47, 0xce,
	0x88, 0x54, 0x6e, 0x0b, 0x76, 0xc7, 0x33, 0xcf, 0xb3, 0x16, 0x0c, 0xf0, 0xa7, 0x85, 0xe5, 0x71,
	0x1d, 0x66, 0xd8, 0x30, 0x62, 0x54, 0x59, 0x19, 0x72, 0x61, 0x2f, 0xb2, 0xc7, 0xc4, 0x8a, 0x78,
	0xd5, 0xa4, 0x9a, 0x10, 0x09, 0xfa, 0x70, 0x89, 0x89, 0x97, 0x55, 0x5c, 0x78, 0x37, 0x7a, 0x59,
	0x1d, 0xe6, 0xc3, 0x1d, 0x91, 0x0b, 0xf3, 0xa2, 0x4d, 0xb5, 0x57, 0x78, 0xad, 0xfd, 0x66, 0xe1,
	0xc4, 0xc4, 0xb7, 0xdd, 0xac, 0x40, 0xb1, 0x37, 0x86, 0x5b, 0xca, 0xae, 0xa6, 0x58, 0x2a, 0x71,
	0x4b, 0xc7, 0xaf, 0xbb, 0xb3, 0xa9, 0x2b, 0xd7, 0x79, 0xc9, 0x59, 0x64, 0x42, 0x25, 0xb3, 0xc3,
	0xf1, 0x67, 0x99, 0xe5, 0x39, 0xae, 0x6e, 0x6d, 0xb8, 0xac, 0x6e, 0x6a, 0xac, 0xbc, 0x21, 0x61,
	0x48, 0x43, 0x5e, 0xa4, 0x29, 0xe5, 0x4d, 0x18, 0x38, 0x8d, 0x01, 0x7f, 0xb6, 0xc7, 0xa2, 0x83,
	0x3e, 0x85, 0xfd, 0x96, 0x1d, 0xa7, 0x6e, 0x16, 0x3b, 0x42, 0x94, 0xec, 0x7e, 0x7d, 0x28, 0x84,
	0xe2, 0x33, 0xd9, 0x09, 0x96, 0x85, 0xf3, 0x65, 0x9b, 0x28, 0x4e, 0x49, 0xf4, 0x6f, 0xe0, 0xce,
	0x4b, 0xcd, 0xc9, 0x1d, 0x08, 0x43, 0x31, 0x94, 0xdf, 0x89, 0xc1, 0x0f, 0x57, 0x33, 0x28, 0xc0,
	0x78, 0x4e, 0xf3, 0x3e, 0x01, 0x50, 0x9e, 0x93, 0x4a, 0xb0, 0x25, 0x9f, 0x51, 0xb4, 0xb7, 0xd8,
	0x2d, 0xf3, 0x33, 0x03, 0x3f, 0xb1, 0x2e, 0x7a, 0xdd, 0xce, 0xa7, 0x46, 0xf7, 0x89, 0x96, 0x43,
	0x65, 0x28, 0xa4, 0xad, 0x3c, 0x6b, 0x99, 0xfd, 0xc1, 0xa0, 0xd3, 0xea, 0x1a, 0xda, 0x1a, 0x02,
	0xd8, 0x94, 0x9a, 0x75, 0x54, 0x83, 0x12, 0x87, 0x4a, 0xc1, 0xc6, 0xf1, 0xb7, 0x39, 0xa8, 0xf2,
	0x31, 0x34, 0x93, 0x7f, 0x81, 0xd0, 0x9f, 0x73, 0xb0, 0xf3, 0x92, 0xd9, 0xa2, 0x9f, 0x2f, 0x2b,
	0x8f, 0xbe, 0x33, 0x20, 0xfb, 0x8f, 0xde, 0x04, 0x2a, 0x3c, 0xa1, 0xbf, 0xf7, 0xdb, 0xbf, 0xfe,
	0xe3, 0xf7, 0xf9, 0xfb, 0xfa, 0xfe, 0xe2, 0x1f, 0x57, 0xd1, 0x23, 0xb9, 0xb6, 0xc9, 0xa3, 0xdc,
	0xfb, 0xad, 0x8f, 0xe1, 0x5d, 0x87, 0x4e, 0x5f, 0x6d, 0xa7, 0xb5, 0x93, 0x9d, 0xaa, 0x19, 0xd2,
	0x98, 0x9a, 0xb9, 0x7f, 0xe7, 0x72, 0x57, 0x9b, 0xfc, 0xcf, 0x9d, 0x87, 0xff, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0x42, 0xd2, 0x4b, 0x32, 0x1b, 0x00, 0x00,
}
