// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/bigtable/admin/cluster/v1/bigtable_cluster_data.proto

package google_bigtable_admin_cluster_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "go.pedge.io/pb/go/google/api"
import google_longrunning "go.pedge.io/pb/go/google/longrunning"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StorageType int32

const (
	// The storage type used is unspecified.
	StorageType_STORAGE_UNSPECIFIED StorageType = 0
	// Data will be stored in SSD, providing low and consistent latencies.
	StorageType_STORAGE_SSD StorageType = 1
	// Data will be stored in HDD, providing high and less predictable
	// latencies.
	StorageType_STORAGE_HDD StorageType = 2
)

var StorageType_name = map[int32]string{
	0: "STORAGE_UNSPECIFIED",
	1: "STORAGE_SSD",
	2: "STORAGE_HDD",
}
var StorageType_value = map[string]int32{
	"STORAGE_UNSPECIFIED": 0,
	"STORAGE_SSD":         1,
	"STORAGE_HDD":         2,
}

func (x StorageType) String() string {
	return proto.EnumName(StorageType_name, int32(x))
}
func (StorageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Possible states of a zone.
type Zone_Status int32

const (
	// The state of the zone is unknown or unspecified.
	Zone_UNKNOWN Zone_Status = 0
	// The zone is in a good state.
	Zone_OK Zone_Status = 1
	// The zone is down for planned maintenance.
	Zone_PLANNED_MAINTENANCE Zone_Status = 2
	// The zone is down for emergency or unplanned maintenance.
	Zone_EMERGENCY_MAINENANCE Zone_Status = 3
)

var Zone_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "PLANNED_MAINTENANCE",
	3: "EMERGENCY_MAINENANCE",
}
var Zone_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"OK":      1,
	"PLANNED_MAINTENANCE":  2,
	"EMERGENCY_MAINENANCE": 3,
}

func (x Zone_Status) String() string {
	return proto.EnumName(Zone_Status_name, int32(x))
}
func (Zone_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// A physical location in which a particular project can allocate Cloud BigTable
// resources.
type Zone struct {
	// A permanent unique identifier for the zone.
	// Values are of the form projects/<project>/zones/[a-z][-a-z0-9]*
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The name of this zone as it appears in UIs.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	// The current state of this zone.
	Status Zone_Status `protobuf:"varint,3,opt,name=status,enum=google.bigtable.admin.cluster.v1.Zone_Status" json:"status,omitempty"`
}

func (m *Zone) Reset()                    { *m = Zone{} }
func (m *Zone) String() string            { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()               {}
func (*Zone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Zone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Zone) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Zone) GetStatus() Zone_Status {
	if m != nil {
		return m.Status
	}
	return Zone_UNKNOWN
}

// An isolated set of Cloud BigTable resources on which tables can be hosted.
type Cluster struct {
	// A permanent unique identifier for the cluster. For technical reasons, the
	// zone in which the cluster resides is included here.
	// Values are of the form
	// projects/<project>/zones/<zone>/clusters/[a-z][-a-z0-9]*
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The operation currently running on the cluster, if any.
	// This cannot be set directly, only through CreateCluster, UpdateCluster,
	// or UndeleteCluster. Calls to these methods will be rejected if
	// "current_operation" is already set.
	CurrentOperation *google_longrunning.Operation `protobuf:"bytes,3,opt,name=current_operation,json=currentOperation" json:"current_operation,omitempty"`
	// The descriptive name for this cluster as it appears in UIs.
	// Must be unique per zone.
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	// The number of serve nodes allocated to this cluster.
	ServeNodes int32 `protobuf:"varint,5,opt,name=serve_nodes,json=serveNodes" json:"serve_nodes,omitempty"`
	// What storage type to use for tables in this cluster. Only configurable at
	// cluster creation time. If unspecified, STORAGE_SSD will be used.
	DefaultStorageType StorageType `protobuf:"varint,8,opt,name=default_storage_type,json=defaultStorageType,enum=google.bigtable.admin.cluster.v1.StorageType" json:"default_storage_type,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetCurrentOperation() *google_longrunning.Operation {
	if m != nil {
		return m.CurrentOperation
	}
	return nil
}

func (m *Cluster) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Cluster) GetServeNodes() int32 {
	if m != nil {
		return m.ServeNodes
	}
	return 0
}

func (m *Cluster) GetDefaultStorageType() StorageType {
	if m != nil {
		return m.DefaultStorageType
	}
	return StorageType_STORAGE_UNSPECIFIED
}

func init() {
	proto.RegisterType((*Zone)(nil), "google.bigtable.admin.cluster.v1.Zone")
	proto.RegisterType((*Cluster)(nil), "google.bigtable.admin.cluster.v1.Cluster")
	proto.RegisterEnum("google.bigtable.admin.cluster.v1.StorageType", StorageType_name, StorageType_value)
	proto.RegisterEnum("google.bigtable.admin.cluster.v1.Zone_Status", Zone_Status_name, Zone_Status_value)
}

func init() {
	proto.RegisterFile("google/bigtable/admin/cluster/v1/bigtable_cluster_data.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x1c, 0xc5, 0x97, 0xac, 0xeb, 0xc0, 0x41, 0x10, 0xcc, 0x24, 0xa2, 0x09, 0xb4, 0x52, 0x38, 0x54,
	0x48, 0x24, 0xda, 0xb8, 0x72, 0x69, 0x1b, 0xb3, 0x95, 0x31, 0x37, 0x4a, 0x3a, 0x21, 0xb8, 0x58,
	0x6e, 0xe3, 0x45, 0x91, 0x12, 0x3b, 0x8a, 0x9d, 0x4a, 0xfd, 0x12, 0x7c, 0x3c, 0x3e, 0x0f, 0x8a,
	0xe3, 0x56, 0x45, 0x43, 0xda, 0x6e, 0xf1, 0xfb, 0xbd, 0x67, 0xe7, 0xff, 0x6c, 0xf0, 0x25, 0x13,
	0x22, 0x2b, 0x58, 0xb0, 0xcc, 0x33, 0x45, 0x97, 0x05, 0x0b, 0x68, 0x5a, 0xe6, 0x3c, 0x58, 0x15,
	0x8d, 0x54, 0xac, 0x0e, 0xd6, 0xe7, 0x3b, 0x42, 0x8c, 0x46, 0x52, 0xaa, 0xa8, 0x5f, 0xd5, 0x42,
	0x09, 0x38, 0xe8, 0xd2, 0xfe, 0xd6, 0xe3, 0xeb, 0xb4, 0x6f, 0x9c, 0xfe, 0xfa, 0xfc, 0xf4, 0x8d,
	0xd9, 0x9f, 0x56, 0x79, 0x40, 0x39, 0x17, 0x8a, 0xaa, 0x5c, 0x70, 0xd9, 0xe5, 0x4f, 0xdf, 0x1b,
	0x5a, 0x08, 0x9e, 0xd5, 0x0d, 0xe7, 0x39, 0xcf, 0x02, 0x51, 0xb1, 0xfa, 0x1f, 0xd3, 0x99, 0x31,
	0xe9, 0xd5, 0xb2, 0xb9, 0x0b, 0x54, 0x5e, 0x32, 0xa9, 0x68, 0x59, 0x75, 0x86, 0xe1, 0x1f, 0x0b,
	0xf4, 0x7e, 0x09, 0xce, 0x20, 0x04, 0x3d, 0x4e, 0x4b, 0xe6, 0x59, 0x03, 0x6b, 0xf4, 0x34, 0xd6,
	0xdf, 0xf0, 0x1d, 0x78, 0x96, 0xe6, 0xb2, 0x2a, 0xe8, 0x86, 0x68, 0x66, 0x6b, 0xe6, 0x18, 0x0d,
	0xb7, 0x16, 0x04, 0xfa, 0x52, 0x51, 0xd5, 0x48, 0xef, 0x70, 0x60, 0x8d, 0x9e, 0x5f, 0x7c, 0xf2,
	0x1f, 0x1a, 0xcb, 0x6f, 0x8f, 0xf3, 0x13, 0x1d, 0x8a, 0x4d, 0x78, 0x18, 0x81, 0x7e, 0xa7, 0x40,
	0x07, 0x1c, 0xdf, 0xe2, 0x6b, 0x3c, 0xff, 0x81, 0xdd, 0x03, 0xd8, 0x07, 0xf6, 0xfc, 0xda, 0xb5,
	0xe0, 0x6b, 0xf0, 0x2a, 0xfa, 0x3e, 0xc6, 0x18, 0x85, 0xe4, 0x66, 0x3c, 0xc3, 0x0b, 0x84, 0xc7,
	0x78, 0x8a, 0x5c, 0x1b, 0x7a, 0xe0, 0x04, 0xdd, 0xa0, 0xf8, 0x12, 0xe1, 0xe9, 0x4f, 0x8d, 0x0c,
	0x39, 0x1c, 0xfe, 0xb6, 0xc1, 0xf1, 0xb4, 0x3b, 0xf4, 0xbf, 0xb3, 0x7d, 0x03, 0x2f, 0x57, 0x4d,
	0x5d, 0x33, 0xae, 0xc8, 0xae, 0x35, 0x3d, 0x83, 0x73, 0xf1, 0x76, 0x3b, 0xc3, 0x5e, 0xb5, 0xfe,
	0x7c, 0x6b, 0x8a, 0x5d, 0x93, 0xdb, 0x29, 0xf7, 0x7a, 0xea, 0xdd, 0xef, 0xe9, 0x0c, 0x38, 0x92,
	0xd5, 0x6b, 0x46, 0xb8, 0x48, 0x99, 0xf4, 0x8e, 0x06, 0xd6, 0xe8, 0x28, 0x06, 0x5a, 0xc2, 0xad,
	0x02, 0x09, 0x38, 0x49, 0xd9, 0x1d, 0x6d, 0x0a, 0x45, 0xa4, 0x12, 0x35, 0xcd, 0x18, 0x51, 0x9b,
	0x8a, 0x79, 0x4f, 0x1e, 0x5b, 0x6b, 0xd2, 0xa5, 0x16, 0x9b, 0x8a, 0xc5, 0xd0, 0x6c, 0xb5, 0xa7,
	0x7d, 0xbc, 0x02, 0xce, 0xde, 0xb2, 0xad, 0x34, 0x59, 0xcc, 0xe3, 0xf1, 0x25, 0x22, 0xb7, 0x38,
	0x89, 0xd0, 0x74, 0xf6, 0x75, 0x86, 0x42, 0xf7, 0x00, 0xbe, 0x00, 0xce, 0x16, 0x24, 0x49, 0xe8,
	0x5a, 0xfb, 0xc2, 0x55, 0x18, 0xba, 0xf6, 0x64, 0x02, 0x3e, 0xac, 0x44, 0xf9, 0xe0, 0x1f, 0x4d,
	0xbc, 0x89, 0x41, 0xe6, 0x1e, 0x42, 0xaa, 0x68, 0xd4, 0xbe, 0xba, 0xc8, 0x5a, 0xf6, 0xf5, 0xf3,
	0xfb, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x61, 0xe4, 0x1c, 0xcc, 0x44, 0x03, 0x00, 0x00,
}
